FIX: agents-PID and cibadmin race conditions

diff --git a/deployment/puppet/quantum/files/ocf/quantum-agent-metadata b/deployment/puppet/quantum/files/ocf/quantum-agent-metadata
--- a/deployment/puppet/quantum/files/ocf/quantum-agent-metadata
+++ b/deployment/puppet/quantum/files/ocf/quantum-agent-metadata
@@ -151,6 +151,11 @@ The debug flag for  OpenStack Metadata Service (quantum-metadata-agent) instance
 END
 }
 
+get_worker_pid() {
+    pid=`pgrep -u ${OCF_RESKEY_user} -fnl ${OCF_RESKEY_binary} | grep -E  "python\s+\/usr\/bin" | awk '{print $1}'`
+    echo $pid
+}
+
 #######################################################################
 # Functions invoked by resource manager actions
 
@@ -181,45 +186,50 @@ quantum_metadata_agent_validate() {
 }
 
 quantum_metadata_agent_status() {
-    local pid
+   local pid
+    local f_pid
     local rc
 
-    if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Quantum Metadata Agent (quantum-metadata-agent) seems not to exist"
-
-        pid=`pgrep -f ${OCF_RESKEY_binary}`
-
-        if [ $? -eq 0 ]
-        then
-            ocf_log warn "OpenStack Quantum Metadata Agent (quantum-metadata-agent) was run, but no pid file found."
-            ocf_log warn "Will use $pid as PID of process (quantum-metadata-agent)"
-            ocf_log warn "Writing $pid into $OCF_RESKEY_pid"
-            echo $pid > $OCF_RESKEY_pid
-        else
-            return $OCF_NOT_RUNNING
-        fi
-    else
-        pid=`cat $OCF_RESKEY_pid`
-    fi
-
-    ocf_run -warn kill -s 0 $pid
-    rc=$?
-    if [ $rc -eq 0 ]; then
-        return $OCF_SUCCESS
-    else
-        ocf_log info "Old PID file $OCF_RESKEY_pid found (with pid $pid), but OpenStack Quantum Metadata Agent (quantum-metadata-agent) is not running"
+    pid=`get_worker_pid`
+    if [ "xxx$pid" == "xxx" ] ; then
+        ocf_log warn "OpenStack Quantum agent '$OCF_RESKEY_binary' not running."
         return $OCF_NOT_RUNNING
     fi
+    #ocf_log debug "PID='$pid'"
+
+    # Check PID file and create if need
+    if [ ! -f $OCF_RESKEY_pid ] ; then
+        ocf_log warn "OpenStack Quantum agent (${OCF_RESKEY_binary}) was run, but no PID file found."
+        ocf_log warn "Writing PID='$pid' to '$OCF_RESKEY_pid' for '${OCF_RESKEY_binary}' worker..."
+        echo $pid > $OCF_RESKEY_pid
+        return $OCF_SUCCESS
+    fi
+
+    # compare PID from file with PID from `pgrep...`
+    f_pid=`cat $OCF_RESKEY_pid | tr '\n' ' ' | awk '{print $1}'`
+    if [ "xxx$pid" == "xxx$f_pid" ]; then
+        return $OCF_SUCCESS
+    fi
+
+    # at this point we have PID file and PID from it
+    # defferents with PID from `pgrep...`
+    if [ ! -d "/proc/$f_pid" ] || [ "xxx$f_pid" == "xxx" ] ; then
+        # process with PID from PID-file not found
+        ocf_log warn "Old PID file $OCF_RESKEY_pid found, but no running processes with PID=$f_pid found."
+        ocf_log warn "PID-file will be re-created (with PID=$pid)."
+        echo $pid > $OCF_RESKEY_pid
+        return $OCF_SUCCESS
+    fi
+
+    # at this point we have alien PID-file and running prosess with this PID.
+    ocf_log warn "Another daemon (with PID=$f_pid) running with PID file '$OCF_RESKEY_pid'. My PID=$pid"
+    return $OCF_ERR_GENERIC
 }
 
 quantum_metadata_agent_monitor() {
     quantum_metadata_agent_status
     rc=$?
     return $rc
-}
-
-clean_up() {
-	ocf_log info "cleaning up quantum-metadata-agent. nothing to do."
 }
 
 quantum_metadata_agent_start() {
@@ -231,25 +241,23 @@ quantum_metadata_agent_start() {
         return $OCF_SUCCESS
     fi
 
-    clean_up
-
-    # run the actual quantum-metadata-agent daemon. Don't use ocf_run as we're sending the tool's output
-    # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
+    # run and detach to background quantum-metadata-agent as daemon.
+    # Don't use ocf_run as we're sending the tool's output
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
       --config-file=$OCF_RESKEY_agent_config $OCF_RESKEY_additional_parameters \
-      >> ${OCF_RESKEY_log_file}"' 2>&1 & echo $!' > $OCF_RESKEY_pid
+      >> ${OCF_RESKEY_log_file}"' 2>&1 &'
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    quantum_metadata_agent_monitor
-    rc=$?
-    [ $rc -eq $OCF_SUCCESS ] && break
-    if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Quantum Metadata Agent (quantum-metadata-agent) start failed"
-        exit $OCF_ERR_GENERIC
-    fi
-    sleep 1
+        quantum_metadata_agent_monitor
+        rc=$?
+        [ $rc -eq $OCF_SUCCESS ] && break
+        if [ $rc -ne $OCF_NOT_RUNNING ] ; then
+            ocf_log err "OpenStack (${OCF_RESKEY_binary}) start failed"
+            exit $OCF_ERR_GENERIC
+        fi
+        sleep 3
     done
 
     ocf_log info "OpenStack Quantum Metadata Agent (quantum-metadata-agent) started"
@@ -263,7 +271,6 @@ quantum_metadata_agent_stop() {
     quantum_metadata_agent_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        clean_up
         ocf_log info "OpenStack Quantum Metadata Agent (quantum-metadata-agent) already stopped"
         return $OCF_SUCCESS
     fi
@@ -302,8 +309,6 @@ quantum_metadata_agent_stop() {
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-
-    clean_up
 
     ocf_log info "OpenStack Quantum Metadata Agent (quantum-metadata-agent) stopped"
 
