Rescheduling Networks to another DHCP agent
* refactor calls to Quantum API
* add --remove-dead. remove dead agents after rescheduling
* healthy check for dhcp agent (trough API)
* rescheduling networks after succeffuly start agent (in ocf-script)

diff --git a/deployment/puppet/quantum/files/ocf/quantum-agent-dhcp b/deployment/puppet/quantum/files/ocf/quantum-agent-dhcp
--- a/deployment/puppet/quantum/files/ocf/quantum-agent-dhcp
+++ b/deployment/puppet/quantum/files/ocf/quantum-agent-dhcp
@@ -243,9 +243,18 @@ quantum_dhcp_agent_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file $OCF_RESKEY_pid found (with pid $pid), but OpenStack OVS Server (quantum-dhcp-agent) is not running"
+        ocf_log info "Old PID file $OCF_RESKEY_pid found (with pid $pid), but quantum-dhcp-agent is not running"
         return $OCF_NOT_RUNNING
     fi
+
+    # ocf_run q-agent-cleanup.py --agent=dhcp --test-alive-for-hostname=`hostname` --test-alive-for-hostname=`hostname -f`
+    # rc=$?
+    # if [ $rc -eq 0 ]; then
+    #     return $OCF_SUCCESS
+    # else
+    #     ocf_log info "quantum-dhcp-agent (with pid $pid) running, but quantum-server means that agent dead."
+    #     return $OCF_ERR_GENERIC
+    # fi
 }
 
 
@@ -283,15 +292,17 @@ quantum_dhcp_agent_start() {
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    quantum_dhcp_agent_monitor
-    rc=$?
-    [ $rc -eq $OCF_SUCCESS ] && break
-    if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack DHCP Server (quantum-dhcp-agent) start failed"
-        exit $OCF_ERR_GENERIC
-    fi
-    sleep 1
+        quantum_dhcp_agent_monitor
+        rc=$?
+        [ $rc -eq $OCF_SUCCESS ] && break
+        if [ $rc -ne $OCF_NOT_RUNNING ]; then
+            ocf_log err "OpenStack DHCP Server (quantum-dhcp-agent) start failed"
+            exit $OCF_ERR_GENERIC
+        fi
+        sleep 1
     done
+
+    q-agent-cleanup.py --agent=dhcp --reschedule --remove-dead
 
     ocf_log info "OpenStack DHCP Server (quantum-dhcp-agent) started"
     return $OCF_SUCCESS
