refactor ocf scripts for DHCP and L3 agents
* l3 and dhcp agents ocf files now stores in Quantum module
* new cleanup script

diff --git a/deployment/puppet/quantum/files/ocf/quantum-agent-l3 b/deployment/puppet/quantum/files/ocf/quantum-agent-l3
--- a/deployment/puppet/quantum/files/ocf/quantum-agent-l3
+++ b/deployment/puppet/quantum/files/ocf/quantum-agent-l3
@@ -1,9 +1,9 @@
 #!/bin/bash
 #
 #
-# OpenStack DHCP Service (quantum-dhcp-agent)
+# OpenStack L3 Service (quantum-l3-agent)
 #
-# Description:  Manages an OpenStack DHCP Service (quantum-dhcp-agent) process as an HA resource
+# Description:  Manages an OpenStack L3 Service (quantum-l3-agent) process as an HA resource
 #
 # Authors: Emilien Macchi
 # Mainly inspired by the Nova Network resource agent written by Emilien Macchi & Sebastien Han
@@ -20,7 +20,7 @@
 #   OCF_RESKEY_plugin_config
 #   OCF_RESKEY_user
 #   OCF_RESKEY_pid
-#   OCF_RESKEY_amqp_server_port
+#   OCF_RESKEY_quantum_server_port
 #   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
@@ -32,15 +32,17 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="quantum-dhcp-agent"
+OCF_RESKEY_binary_default="quantum-l3-agent"
 OCF_RESKEY_config_default="/etc/quantum/quantum.conf"
-OCF_RESKEY_plugin_config_default="/etc/quantum/dhcp_agent.ini"
+OCF_RESKEY_plugin_config_default="/etc/quantum/l3_agent.ini"
 OCF_RESKEY_user_default="quantum"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
 OCF_RESKEY_os_auth_url_default="http://localhost:5000/v2.0"
 OCF_RESKEY_username_default="quantum"
 OCF_RESKEY_password_default="quantum_pass"
 OCF_RESKEY_tenant_default="services"
+OCF_RESKEY_external_bridge_default="br-ex"
+
 
 : ${OCF_RESKEY_os_auth_url=${OCF_RESKEY_os_auth_url_default}}
 : ${OCF_RESKEY_username=${OCF_RESKEY_username_default}}
@@ -51,6 +53,7 @@ OCF_RESKEY_tenant_default="services"
 : ${OCF_RESKEY_plugin_config=${OCF_RESKEY_plugin_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
+: ${OCF_RESKEY_external_bridge=${OCF_RESKEY_external_bridge_default}}
 
 
 
@@ -60,7 +63,7 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack DHCP Service (quantum-dhcp-agent) process as an HA resource 
+        $0 manages an OpenStack L3 Service (quantum-l3-agent) process as an HA resource 
 
         The 'start' operation starts the networking service.
         The 'stop' operation stops the networking service.
@@ -76,22 +79,22 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="quantum-dhcp-agent">
+<resource-agent name="quantum-l3-agent">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Quantum DHCP Service (quantum-dhcp-agent)
-May manage a quantum-dhcp-agent instance or a clone set that 
-creates a distributed quantum-dhcp-agent cluster.
+Resource agent for the OpenStack Quantum L3 Service (quantum-l3-agent)
+May manage a quantum-l3-agent instance or a clone set that 
+creates a distributed quantum-l3-agent cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack DHCP Service (quantum-dhcp-agent)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack L3 Service (quantum-l3-agent)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack DHCP Server server binary (quantum-dhcp-agent)
+Location of the OpenStack L3 Server server binary (quantum-l3-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server server binary (quantum-dhcp-agent)</shortdesc>
+<shortdesc lang="en">OpenStack L3 Server server binary (quantum-l3-agent)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
@@ -99,33 +102,42 @@ Location of the OpenStack DHCP Server server binary (quantum-dhcp-agent)
 <longdesc lang="en">
 Location of the OpenStack Quantum Service (quantum-server) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (quantum-server) config file</shortdesc>
+<shortdesc lang="en">OpenStack L3 Server (quantum-server) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="plugin_config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack DHCP Service (quantum-dhcp-agent) configuration file
+Location of the OpenStack L3 Service (quantum-l3-agent) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (quantum-dhcp-agent) config file</shortdesc>
+<shortdesc lang="en">OpenStack L3 Server (quantum-l3-agent) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_plugin_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack DHCP Service (quantum-dhcp-agent)
+User running OpenStack L3 Service (quantum-l3-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Service (quantum-dhcp-agent) user</shortdesc>
+<shortdesc lang="en">OpenStack L3 Service (quantum-l3-agent) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack DHCP Service (quantum-dhcp-agent) instance
+The pid file to use for this OpenStack L3 Service (quantum-l3-agent) instance
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Service (quantum-dhcp-agent) pid file</shortdesc>
+<shortdesc lang="en">OpenStack L3 Service (quantum-l3-agent) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>  
+
+<parameter name="quantum_server_port" unique="0" required="0">                                                                                                                                                              
+<longdesc lang="en">                                                                                                                                                                                                      
+The listening port number of the AMQP server. Mandatory to perform a monitor check                                                                                                                                        
+</longdesc>                                                                                                                                                                                                               
+<shortdesc lang="en">AMQP listening port</shortdesc>                                                                                                                                                                      
+<content type="integer" default="${OCF_RESKEY_quantum_server_port_default}" />                                                                                                                                              
+</parameter>      
+
 
 <parameter name="username" unique="0" required="0">                                                                                                                                                              
 <longdesc lang="en">                                                                                                                                                                                                      
@@ -160,12 +172,21 @@ Admin tenant name
 <content type="string" default="${OCF_RESKEY_tenant_default}" />                                                                                                                                              
 </parameter>      
 
+<parameter name="external_bridge" unique="0" required="0">
+<longdesc lang="en">
+External bridge for l3-agent
+</longdesc>
+<shortdesc lang="en">External bridge</shortdesc>
+<content type="string" />
+</parameter>
+
+
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack DHCP Service (quantum-dhcp-agent)
+Additional parameters to pass on to the OpenStack L3 Service (quantum-l3-agent)
 </longdesc>
-<shortdesc lang="en">Additional parameters for quantum-dhcp-agent</shortdesc>
+<shortdesc lang="en">Additional parameters for quantum-l3-agent</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -188,7 +209,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-quantum_dhcp_agent_validate() {
+quantum_l3_agent_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
@@ -214,19 +235,19 @@ quantum_dhcp_agent_validate() {
     true
 }
 
-quantum_dhcp_agent_status() {
+quantum_l3_agent_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack OVS Server (quantum-dhcp-agent) seems not to exist"
+        ocf_log info "OpenStack OVS Server (quantum-l3-agent) seems not to exist"
         
         pid=`pgrep -f ${OCF_RESKEY_binary}`
         
         if [ $? -eq 0 ]
         then
-        	ocf_log warn "OpenStack OVS Server (quantum-dhcp-agent) was run, but no pid file found."
-        	ocf_log warn "Will use $pid as PID of process (quantum-dhcp-agent)"
+        	ocf_log warn "OpenStack OVS Server (quantum-l3-agent) was run, but no pid file found."
+        	ocf_log warn "Will use $pid as PID of process (quantum-l3-agent)"
         	ocf_log warn "Writing $pid into $OCF_RESKEY_pid"
         	echo $pid > $OCF_RESKEY_pid
     	else
@@ -241,7 +262,7 @@ quantum_dhcp_agent_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file $OCF_RESKEY_pid found (with pid $pid), but OpenStack OVS Server (quantum-dhcp-agent) is not running"
+        ocf_log info "Old PID file found, but OpenStack OVS Server (quantum-l3-agent) is not running"
         return $OCF_NOT_RUNNING
     fi
 }
@@ -250,37 +271,30 @@ quantum_dhcp_agent_status() {
 
 clean_up()
 {
-    filter_quantum_ports.py "network:dhcp" | while read port ip; do
-        ocf_log info "Cleaning up port ${port}"
-        ovs-vsctl -- --if-exists del-port ${port};
-        rc=$?
-        if [ $rc -ne 0 ]; then
-            ocf_log err "Could not cleanup port ${port}"
-            exit $OCF_ERR_GENERIC
-        fi
-	 done
+    q-agent-cleanup.py --debug --agent=l3 --cleanup-ports --remove-agent
 }
 
 
-quantum_dhcp_agent_monitor() {
-    quantum_dhcp_agent_status
+quantum_l3_agent_monitor() {
+    quantum_l3_agent_status
     rc=$?
     return $rc
+
 }
 
-quantum_dhcp_agent_start() {
+quantum_l3_agent_start() {
     local rc
-    
-    clean_up
-    
-    quantum_dhcp_agent_status
+	
+    quantum_l3_agent_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack DHCP Server (quantum-dhcp-agent) already running"
+        ocf_log info "OpenStack L3 Server (quantum-l3-agent) already running"
         return $OCF_SUCCESS
     fi
+    
+    clean_up
 
-    # run the actual quantum-dhcp-agent daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual quantum-l3-agent daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
        --config-file=$OCF_RESKEY_plugin_config $OCF_RESKEY_additional_parameters"' >> \
@@ -289,39 +303,38 @@ quantum_dhcp_agent_start() {
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    quantum_dhcp_agent_monitor
+    quantum_l3_agent_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack DHCP Server (quantum-dhcp-agent) start failed"
+        ocf_log err "OpenStack L3 Server (quantum-l3-agent) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack DHCP Server (quantum-dhcp-agent) started"
+    ocf_log info "OpenStack L3 Server (quantum-l3-agent) started"
     return $OCF_SUCCESS
 }
 
-quantum_dhcp_agent_stop() {
+quantum_l3_agent_stop() {
     local rc
     local pid
 
-    quantum_dhcp_agent_status
+    quantum_l3_agent_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
     	clean_up
-        ocf_log info "OpenStack DHCP Server (quantum-dhcp-agent) already stopped"
+        ocf_log info "OpenStack L3 Server (quantum-l3-agent) already stopped"
         return $OCF_SUCCESS
     fi
 
-    #Try SIGTERM
+    # Try SIGTERM
     pid=`cat $OCF_RESKEY_pid`
-    pid="$pid `ps ax | grep -v grep | grep 'dnsmasq' | cut -c1-5`"
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack DHCP Server (quantum-dhcp-agent) couldn't be stopped"
+        ocf_log err "OpenStack L3 Server (quantum-l3-agent) couldn't be stopped"
         exit $OCF_ERR_GENERIC
     fi
 
@@ -332,29 +345,31 @@ quantum_dhcp_agent_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        quantum_dhcp_agent_status
+        quantum_l3_agent_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack DHCP Server (quantum-dhcp-agent) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack L3 Server (quantum-l3-agent) still hasn't stopped yet. Waiting ..."
     done
 
-    quantum_dhcp_agent_status
+    quantum_l3_agent_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack DHCP Server (quantum-dhcp-agent) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack L3 Server (quantum-l3-agent) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-	clean_up
-    ocf_log info "OpenStack DHCP Server (quantum-dhcp-agent) stopped"
+
+    ocf_log info "OpenStack L3 Server (quantum-l3-agent) stopped"
 
     rm -f $OCF_RESKEY_pid
-
+	
+	clean_up
+	
     return $OCF_SUCCESS
 }
 
@@ -368,14 +383,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-quantum_dhcp_agent_validate || exit $?
+quantum_l3_agent_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        quantum_dhcp_agent_start;;
-  stop)         quantum_dhcp_agent_stop;;
-  status)       quantum_dhcp_agent_status;;
-  monitor)      quantum_dhcp_agent_monitor;;
+  start)        quantum_l3_agent_start;;
+  stop)         quantum_l3_agent_stop;;
+  status)       quantum_l3_agent_status;;
+  monitor)      quantum_l3_agent_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
