Add more checks to OCF scripts
This commit introduces new health checks in OCF scripts.
ns_haproxy:
        Added checking responsiveness by reading from the stats socket
        which listens by default on the management VIP. This check works
        only on the node which has the management VIP at the moment.
ns_IPAddr2:
        Added a ping check to make sure we have working L3+
        connectivity.

Although this conditions are extremely rare to occur it would be better
to check resources more deeply.

Co-Authored-By: Alexey Zvyagintsev <azvyagintsev@mirantis.com>

Change-Id: I92b6ab06f13b47740e417c8780254daa07799b77
Closes-Bug: #1704657

diff --git a/files/fuel-ha-utils/ocf/ns_haproxy b/files/fuel-ha-utils/ocf/ns_haproxy
--- a/files/fuel-ha-utils/ocf/ns_haproxy
+++ b/files/fuel-ha-utils/ocf/ns_haproxy
@@ -397,6 +397,39 @@ set_ns_routing() {
   fi
 }
 
+haproxy_get_stats() {
+# this function checks if this node has the b_management interface
+# (i.e. the VIP is on this node) then checks if the haproxy process
+# is reponsive by getting its statistics from the management socket
+# Currently, haproxy stats always listen on http.
+
+  local MGMT_PORT
+  local MGMT_IP
+  local EC
+
+  MGMT_PORT=10000
+  MGMT_IP=$(ip netns exec haproxy ip -f inet addr show dev b_management | grep -Po "inet \K[\d.]+")
+  EC=$?
+
+  if [[ $EC -ne 0 ]]; then
+    # we do not have VIP here so it is ok to return OCF_SUCCESS
+    ocf_log info "haproxy daemon running as slave"
+    return $OCF_SUCCESS
+  fi
+
+  curl -m 5 --connect-timeout 5 -s -o /dev/null "http://${MGMT_IP}:${MGMT_PORT}/"
+  EC=$?
+
+  if [[ $EC -ne 0  ]]; then
+    # our check failed
+    ocf_log err "haproxy does not respond on statistics socket"
+    return $OCF_ERR_GENERIC
+  else
+    ocf_log info "haproxy is running and responsive"
+    return $OCF_SUCCESS
+  fi
+}
+
 haproxy_status() {
 	get_variables
 
@@ -416,8 +449,8 @@ haproxy_status() {
 		if [ -n "${PID}" ]; then
 			# check if process exists
 			if $RUN ps -p "${PID}" | grep -q haproxy; then
-				ocf_log info "haproxy daemon running"
-				return $OCF_SUCCESS
+				haproxy_get_stats
+				return $?
 			else
 				ocf_log warn "haproxy daemon is not running but pid file exists"
 				return $OCF_NOT_RUNNING
