Add more checks to OCF scripts
This commit introduces new health checks in OCF scripts.
ns_haproxy:
        Added checking responsiveness by reading from the stats socket
        which listens by default on the management VIP. This check works
        only on the node which has the management VIP at the moment.
        Misc: fix bash comprehension
ns_IPAddr2:
        Added a ping check to make sure we have working L3+
        connectivity.

Although this conditions are extremely rare to occur it would be better
to check resources more deeply.

Co-Authored-By: Alexey Zvyagintsev <azvyagintsev@mirantis.com>

Change-Id: I92b6ab06f13b47740e417c8780254daa07799b77
Closes-Bug: #1704657

diff --git a/files/fuel-ha-utils/ocf/ns_IPaddr2 b/files/fuel-ha-utils/ocf/ns_IPaddr2
--- a/files/fuel-ha-utils/ocf/ns_IPaddr2
+++ b/files/fuel-ha-utils/ocf/ns_IPaddr2
@@ -559,7 +559,12 @@ ip_monitor() {
     # use arping here, because no IP from VIP network allowed on host system
     ocf_run arping -c 10 -w 2 -I $OCF_RESKEY_bridge $OCF_RESKEY_ip ; rc=$?
     if [[ $rc != 0 ]] ; then
-      ocf_log err "VIP '${OCF_RESKEY_ip}' can't be pinged from host. Something went wrong."
+      ocf_log err "VIP ${OCF_RESKEY_ip} can't be arpinged from host. Something went wrong."
+      rv=$OCF_ERR_GENERIC
+    fi
+    ocf_run ping -c 3 -W 2 -I $OCF_RESKEY_bridge $OCF_RESKEY_ip ; rc=$?
+    if [[ $rc -ne 0 ]]; then
+      ocf_log err "VIP ${OCF_RESKEY_ip} can't be pinged from host. Something went wrong."
       rv=$OCF_ERR_GENERIC
     fi
   fi
