Backport OCF/PAM security limits fixes
* Fix missing OCF logging
  (cherry picked from commit 6d90814c5675353aaf97946a40eb92d55cb9bdb4)
* Remove exit code verification from MySQL OCF
  (cherry picked from commit 14ec4750e763d82ab89f0b315f0d4f1341e893d6)
* Check for Mysql wss constraints among online nodes
  (cherry picked from commit 7050f07fe155e00fd1d3bcbf2658de56c3b25387)
* Refactor MySQL OCF script
  (cherry picked from commit 615a0428e3250cffadbf5ebf61e477e91858cb16)
* Update OCF stop actions to use procfs
  (cherry picked from commit 7c210ee68db112bbd16066a54bfdf462a8bbedbd)
* Fix the proc_kill ocf helper func
  (cherry picked from commit d961691e5fa7ba49305e35a4c17de09b2dae2eb6)
* Add pkill by name to the ocf-fuel-funcs
  (cherry picked from commit d5a370e8eb723dcfa28795b089d9f247f51ef105)
* Apply PAM security limits by running daemons through su
  (cherry picked from commit 65eca547606edceedc15d8fadfd1e5822ba9f1f6)

Change-Id: Ie64b4d89c3e3b9aa360a4175416c866ed1ae2620
Closes-bug: #1487083
Closes-bug: #1505735
Closes-bug: #1524826
Closes-bug: #1542256
Partial-bug: #1425579
Closes-bug: #1528889
Partial-bug: #1532723
Closes-bug: #1429553
(cherry picked from commit aa7e4cc0829fed1206f0641822079ede3d1eaba6)

diff --git a/files/fuel-ha-utils/ocf/ocf-neutron-dhcp-agent b/files/fuel-ha-utils/ocf/ocf-neutron-dhcp-agent
--- a/files/fuel-ha-utils/ocf/ocf-neutron-dhcp-agent
+++ b/files/fuel-ha-utils/ocf/ocf-neutron-dhcp-agent
@@ -30,6 +30,8 @@
 
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
+: ${OCF_FUEL_FUNCTIONS_DIR=${OCF_ROOT}/resource.d/fuel}
+. ${OCF_FUEL_FUNCTIONS_DIR}/ocf-fuel-funcs
 
 #######################################################################
 
@@ -418,6 +420,11 @@ neutron_dhcp_agent_start() {
 neutron_dhcp_agent_stop() {
     local rc
     local pid
+    local shutdown_timeout=15
+    if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
+        shutdown_timeout=$(( ($OCF_RESKEY_CRM_meta_timeout/1000) ))
+    fi
+
     # This variable is overridden by reload operation
     # to perform fast resource restart
     local remove_artifacts_on_stop_start=${1:-$OCF_RESKEY_remove_artifacts_on_stop_start}
@@ -434,38 +441,12 @@ neutron_dhcp_agent_stop() {
 
     # Terminate agent daemon
     pid=`get_worker_pid`
-    shutdown_timeout=15
-    iteration_time=1
-
-    if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
-        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-6))
+    proc_stop "${pid}" "${OCF_RESKEY_binary}" $shutdown_timeout
+    rc=$?
+    if [ "${rc}" -eq "${OCF_ERR_GENERIC}" ]; then
+        ocf_log err "OpenStack DHCP Agent (${OCF_RESKEY_binary}) stop failed"
+        return $OCF_ERR_GENERIC
     fi
-
-    clock=0
-
-    # Try to terminate gracefully
-    while [ -d /proc/${pid}/ ] && [ $clock -lt $shutdown_timeout ]; do
-        ocf_log debug "Stopping DHCP Agent (${OCF_RESKEY_binary}) gracefully with SIGTERM"
-        ocf_run kill -s TERM ${pid}
-
-        sleep $iteration_time
-        ((clock+=$iteration_time))
-    done
-
-    # Send kill signal if process is still up
-    if [ -d /proc/${pid}/ ] ; then
-        ocf_log debug "Killing DHCP Agent (${OCF_RESKEY_binary}) with SIGKILL"
-        ocf_run kill -s KILL ${pid}
-
-        sleep 1
-        if [ -d /proc/${pid}/ ] ; then
-            ocf_log err "OpenStack DHCP Agent (${OCF_RESKEY_binary}) stop failed"
-            return $OCF_ERR_GENERIC
-        fi
-    fi
-
-    ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) stopped"
-
     ocf_log debug "Delete pid file: ${OCF_RESKEY_pid} with content $(cat ${OCF_RESKEY_pid})"
     rm -f $OCF_RESKEY_pid
 
