Test CR
Change-Id: I4f212a25bb53d2c3ee9d58e4db800a6c83786ffe

diff --git a/files/fuel-ha-utils/ocf/rabbitmq b/files/fuel-ha-utils/ocf/rabbitmq
--- a/files/fuel-ha-utils/ocf/rabbitmq
+++ b/files/fuel-ha-utils/ocf/rabbitmq
@@ -1124,27 +1124,25 @@ get_monitor() {
             done
             [ $rc -eq $OCF_ERR_GENERIC ] && ocf_log err "${LH} rabbit node is running out of the cluster"
     else
-      if [ "$OCF_CHECK_LEVEL" -gt 20 ]; then
-            ocf_log info "${LH} rabbit app is not running. checking if there is a master"
-            prev_rc=$rc
-            is_master $THIS_PCMK_NODE
-            i_am_master=$?
-            if [ $i_am_master -eq 0 ]; then
-              ocf_log err "${LH} we are the master and rabbit app is not running. this is a failure"
-              exit $OCF_FAILED_MASTER
+        ocf_log info "${LH} rabbit app is not running. checking if there is a master"
+        prev_rc=$rc
+        is_master $THIS_PCMK_NODE
+        i_am_master=$?
+        if [ $i_am_master -eq 0 ]; then
+          ocf_log err "${LH} we are the master and rabbit app is not running. this is a failure"
+          exit $OCF_FAILED_MASTER
+        fi
+        nodelist=$(get_alive_pacemaker_nodes_but)
+        for node in $nodelist
+        do
+            is_master $node
+            status_master=$?
+            ocf_log info "${LH} fetched master attribute for $node. attr value is ${status_master}"
+            if [ $status_master -eq 0 ] ; then
+                rc=$OCF_ERR_GENERIC
+                ocf_log info "${LH} rabbit app is not running. master is $node. exiting to be restarted by pacemaker"
             fi
-            nodelist=$(get_alive_pacemaker_nodes_but)
-            for node in $nodelist
-            do
-                is_master $node
-                status_master=$?
-                ocf_log info "${LH} fetched master attribute for $node. attr value is ${status_master}"
-                if [ $status_master -eq 0 ] ; then
-                    rc=$OCF_ERR_GENERIC
-                    ocf_log info "${LH} rabbit app is not running. master is $node. exiting to be restarted by pacemaker"
-                fi
-            done
-      fi
+        done
     fi
 
     if [[ $rc == $OCF_ERR_GENERIC ]]; then
