Introduce counter against premature split brain detection
If RabbitMQ process which we consider master dies, Pacemaker will
detect the failure only on the next monitor call. Meanwhile slave
processes might find that they are disconnected from the master and
hence should restart in order to avoid split brain, resulting in
complete cluster downtime. In order to avoid such issue, we allow
a small number of 'split brain' checks to fail, giving Pacemaker
time to discover failed master and react.

Related-Bug: #1559136
Change-Id: I2902fa13a36ff111691df06bf31076eae9074d30

diff --git a/files/fuel-ha-utils/ocf/rabbitmq b/files/fuel-ha-utils/ocf/rabbitmq
--- a/files/fuel-ha-utils/ocf/rabbitmq
+++ b/files/fuel-ha-utils/ocf/rabbitmq
@@ -46,6 +46,7 @@ OCF_RESKEY_erlang_cookie_file_default="/var/lib/rabbitmq/.erlang.cookie"
 OCF_RESKEY_use_fqdn_default=false
 OCF_RESKEY_fqdn_prefix_default=""
 OCF_RESKEY_max_rabbitmqctl_timeouts_default=3
+OCF_RESKEY_max_out_of_cluster_fails_default=5
 OCF_RESKEY_policy_file_default="/usr/local/sbin/set_rabbitmq_policy"
 
 : ${HA_LOGTAG="lrmd"}
@@ -67,6 +68,7 @@ OCF_RESKEY_policy_file_default="/usr/local/sbin/set_rabbitmq_policy"
 : ${OCF_RESKEY_use_fqdn=${OCF_RESKEY_use_fqdn_default}}
 : ${OCF_RESKEY_fqdn_prefix=${OCF_RESKEY_fqdn_prefix_default}}
 : ${OCF_RESKEY_max_rabbitmqctl_timeouts=${OCF_RESKEY_max_rabbitmqctl_timeouts_default}}
+: ${OCF_RESKEY_max_out_of_cluster_fails=${OCF_RESKEY_max_out_of_cluster_fails_default}}
 : ${OCF_RESKEY_policy_file=${OCF_RESKEY_policy_file_default}}
 
 #######################################################################
@@ -288,6 +290,17 @@ If too many timeouts happen in a raw, the monitor call will return with error.
 </longdesc>
 <shortdesc lang="en">Fail only if that many rabbitmqctl timeouts in a row occurred</shortdesc>
 <content type="string" default="${OCF_RESKEY_max_rabbitmqctl_timeouts_default}" />
+</parameter>
+
+<parameter name="max_out_of_cluster_fails" unique="0" required="0">
+<longdesc lang="en">
+In order to detect split brain the script checks that current RabbitMQ node is
+connected to the master one. We declare current node to be split only if
+max_out_of_cluster_fails checks in a row fail. We allow several checks to fail
+without action in order to distinguish split brain and master node failure.
+</longdesc>
+<shortdesc lang="en">Fail only if that many checks found us running disconnected with master</shortdesc>
+<content type="string" default="${OCF_RESKEY_max_out_of_cluster_fails_default}" />
 </parameter>
 
 <parameter name="policy_file" unique="0" required="0">
@@ -1349,6 +1362,35 @@ is_master() {
     return 0
 }
 
+
+# Get crm_attr_name value from Pacemaker
+# Increase it by 1
+# Update Pacemaker value
+# Return the updated value via stdout
+increase_and_return_pacemaker_param() {
+    local crm_attr_name=$1
+
+    local count
+    count=`crm_attribute -N $THIS_PCMK_NODE -l reboot --name $crm_attr_name --query 2>/dev/null`
+    if [ $? -ne 0 ]; then
+        # the crm_attribute exited with error. In that case most probably it printed garbage
+        # instead of the number we need. So defensively assume that it is zero.
+
+        count=0
+    else
+        count=`echo "${count}" | awk '{print $3}' | awk -F "=" '{print $2}' | sed -e '/(null)/d'`
+    fi
+
+    count=$((count+1))
+    # There is a slight chance that this piece of code will be executed twice simultaneously.
+    # As a result, $crm_attr_name's value will be one less than it should be. But we don't need
+    # precise calculation here.
+    ocf_run crm_attribute -N $THIS_PCMK_NODE -l reboot --name $crm_attr_name --update $count
+
+    echo $count
+}
+
+
 # Verify if su_rabbit_cmd exited by timeout by checking its return code.
 # If it did not, return 0. If it did AND it is
 # $OCF_RESKEY_max_rabbitmqctl_timeouts'th timeout in a row,
@@ -1366,22 +1408,7 @@ check_timeouts() {
         return 0
     fi
 
-    local count
-    count=`crm_attribute -N $THIS_PCMK_NODE -l reboot --name $crm_attr_name --query 2>/dev/null`
-    if [ $? -ne 0 ]; then
-        # the crm_attribute exited with error. In that case most probably it printed garbage
-        # instead of the number we need. So defensively assume that it is zero.
-
-        count=0
-    fi
-    count=`echo "${count}" | awk '{print $3}' | awk -F "=" '{print $2}' | sed -e '/(null)/d'`
-
-    count=$((count+1))
-    # There is a slight chance that this piece of code will be executed twice simultaneously.
-    # As a result, $crm_attr_name's value will be one less than it should be. But we don't need
-    # precise calculation here.
-    ocf_run crm_attribute -N $THIS_PCMK_NODE -l reboot --name $crm_attr_name --update $count
-
+    count=$(increase_and_return_pacemaker_param $crm_attr_name)
     if [ $count -lt $OCF_RESKEY_max_rabbitmqctl_timeouts ]; then
         ocf_log warn "${LH} 'rabbitmqctl $op_name' timed out $count of max. $OCF_RESKEY_max_rabbitmqctl_timeouts time(s) in a row. Doing nothing for now."
         return 1
@@ -1460,10 +1487,16 @@ get_monitor() {
                 ocf_log info "${LH} rabbit app is running and is member of healthy cluster"
 
             else
-                # Rabbit is running but is not connected to master
-                # Failing to avoid split brain
-                ocf_log err "${LH} rabbit node is running out of the cluster"
-                rc=$OCF_ERR_GENERIC
+                count=$(increase_and_return_pacemaker_param "rabbit_split_brain_counter")
+
+                if [ $count -lt $OCF_RESKEY_max_out_of_cluster_fails ]; then
+                    ocf_log warn "${LH} rabbit node possibly is running out of the cluster. $count out of max. $OCF_RESKEY_max_out_of_cluster_fails latest checks found us disconnected from the master. Doing nothing for now."
+                else
+                    # Rabbit is running but is not connected to master
+                    # Failing to avoid split brain
+                    ocf_log err "${LH} rabbit node is running out of the cluster. $count out of max. $OCF_RESKEY_max_out_of_cluster_fails latest checks found us disconnected from the master. Returning error to be restarted by Pacemaker."
+                    rc=$OCF_ERR_GENERIC
+                fi
             fi
         fi
     else
@@ -1672,6 +1705,7 @@ action_start() {
     ocf_run crm_attribute -N $THIS_PCMK_NODE -l reboot --name 'rabbit_list_channels_timeouts' --update '0'
     ocf_run crm_attribute -N $THIS_PCMK_NODE -l reboot --name 'rabbit_get_alarms_timeouts' --update '0'
     ocf_run crm_attribute -N $THIS_PCMK_NODE -l reboot --name 'rabbit_list_queues_timeouts' --update '0'
+    ocf_run crm_attribute -N $THIS_PCMK_NODE -l reboot --name 'rabbit_split_brain_counter' --update '0'
     ocf_log info "${LH} Deleting start time attribute"
     ocf_run crm_attribute -N $THIS_PCMK_NODE -l reboot --name 'rabbit-start-time' --delete
     ocf_log info "${LH} Deleting master attribute"
