Fix rabbit OCF demote/stop/promote actions
* When the rabbit node went down, its status remains 'running'
  in mnesia db for a while, so few retries (50 sec of total) are
  required in order to kick and forget this node from the cluster.
  This also requires +50 sec for actions stop & demote timeout.
* The rabbit master score in the CIB is retained after the current
  master moved manually. This is wrong and the score must be reset
  ASAP for post-demote and post-stop as well.
* The demoted node must be kicked from cluster by other nodes
  on post-demote processing.
* Post-demote should stop the rabbit app at the node being demoted as
  this node should be kicked from the cluster by other nodes.
  But it stops the app at the *other* nodes instead.
* The check to join should be only done at the post-start and not at
  the post-promote, otherwise promoting node thinks it is clustered
  with another node vs the check reported as "already clustered".
  (the regression was caused by https://review.openstack.org/184671)

Closes-bug: #1436812
Closes-bug: #1455761

Change-Id: Ib01c1731b4f06e6b643a4bca845828f7db507ad3
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/files/fuel-ha-utils/ocf/rabbitmq b/files/fuel-ha-utils/ocf/rabbitmq
--- a/files/fuel-ha-utils/ocf/rabbitmq
+++ b/files/fuel-ha-utils/ocf/rabbitmq
@@ -587,13 +587,24 @@ unjoin_nodes_from_cluster() {
                 fi
 
                 # unjoin node
+                # when the rabbit node went down, its status
+                # remains 'running' for a while, so few retries are required
+                local tries=0
+                until [ $tries -eq 5 ]; do
+                    ((tries++))
+                    if get_running_nodes | grep -q $(rabbit_node_name $nodename)
+                    then
+                        ocf_log info "${LH} the ${nodename} is alive and cannot be kicked from the cluster yet"
+                    fi
+                    sleep 10
+                done
                 ocf_log info "${LH} Execute forget_cluster_node with timeout: ${TIMEOUT_ARG}"
                 su_rabbit_cmd "${OCF_RESKEY_ctl} forget_cluster_node ${nodename}"
                 rc=$?
                 if [[ $rc == 0 ]] ; then
-                    ocf_log info "${LH} node '${nodename}' unjoined succesfully."
+                   ocf_log info "${LH} node '${nodename}' unjoined succesfully."
                 else
-                    ocf_log info "${LH} unjoining node '${nodename}' failed."
+                   ocf_log warn "${LH} unjoining node '${nodename}' failed."
                 fi
             fi
         done
@@ -1198,16 +1209,8 @@ action_notify() {
         case "$OCF_RESKEY_CRM_meta_notify_operation" in
             promote)
                 ocf_log info "${LH} post-promote begin."
-                check_need_join_to ${OCF_RESKEY_CRM_meta_notify_promote_uname}
-                rc_join=$?
-                if [[ ${rc_join} == $OCF_SUCCESS ]]; then
-                  ocf_log warn "${LH} Going to join node ${OCF_RESKEY_CRM_meta_notify_promote_uname}"
-                  jjj_join ${OCF_RESKEY_CRM_meta_notify_promote_uname}
-                  rc=$?
-                else
-                  ocf_log warn "${LH} We are already clustered with node ${OCF_RESKEY_CRM_meta_notify_promote_uname}"
-                  rc=$OCF_SUCCESS
-                fi
+                jjj_join ${OCF_RESKEY_CRM_meta_notify_promote_uname}
+                rc=$?
                 ocf_log info "${LH} post-promote end."
                 if [[ $rc == $OCF_ERR_GENERIC ]] ; then
                     ocf_log err "${LH} Failed to join the cluster on post-promote. Master resource is failed."
@@ -1219,6 +1222,10 @@ action_notify() {
                 # check did this event from this host
                 my_host "${OCF_RESKEY_CRM_meta_notify_start_uname} ${OCF_RESKEY_CRM_meta_notify_active_uname}"
                 rc=$?
+                if [ -z ${OCF_RESKEY_CRM_meta_notify_master_uname} ] ; then
+                  ocf_log warn "${LH} there is no master running on post-start. Resource is failed."
+                  return $OCF_NOT_RUNNING
+                fi
                 if [[ $rc == $OCF_SUCCESS ]] ; then
                     check_need_join_to ${OCF_RESKEY_CRM_meta_notify_master_uname}
                     rc_join=$?
@@ -1240,8 +1247,17 @@ action_notify() {
             stop)
                 # if rabbitmq-server stops on any another node, we should remove it from cluster (as ordinary operation)
                 ocf_log info "${LH} post-stop begin."
+                my_host "${OCF_RESKEY_CRM_meta_notify_stop_uname}"
+                rc=$?
+                if [[ $rc != $OCF_SUCCESS ]] ; then
+                    # On ohter nodes processing the post-stop, make sure the stopped node will be forgotten
+                    unjoin_nodes_from_cluster "${OCF_RESKEY_CRM_meta_notify_stop_uname}"
+                else
+                    # On the nodes being stopped, reset the master score
+                    ocf_log info "${LH} resetting the master score."
+                    master_score 0
+                fi
                 # always returns OCF_SUCCESS
-                unjoin_nodes_from_cluster "${OCF_RESKEY_CRM_meta_notify_stop_uname}"
                 ocf_log info "${LH} post-stop end."
                 ;;
             demote)
@@ -1250,16 +1266,22 @@ action_notify() {
                 my_host "${OCF_RESKEY_CRM_meta_notify_demote_uname}"
                 rc=$?
                 if [[ $rc != $OCF_SUCCESS ]] ; then
-                   ocf_log info "${LH} master was demoted. stopping RabbitMQ app."
-                   stop_rmq_server_app
-                   rc2=$?
-                   crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --delete
+                    # On ohter nodes processing the post-demote, make sure the demoted node will be forgotten
+                    unjoin_nodes_from_cluster "${OCF_RESKEY_CRM_meta_notify_demote_uname}"
+                else
+                    # On the nodes being demoted, reset the master score
+                    ocf_log info "${LH} resetting the master score."
+                    master_score 0
+                    ocf_log info "${LH} master was demoted. stopping RabbitMQ app."
+                    stop_rmq_server_app
+                    rc2=$?
+                    crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --delete
+                    if [[ $rc2 != $OCF_SUCCESS ]] ; then
+                        ocf_log err "${LH} RMQ-server app can't be stopped on post-demote. Master resource is failed"
+                        exit $OCF_FAILED_MASTER
+                    fi
                 fi
                 ocf_log info "${LH} post-demote end."
-                if [[ $rc2 != $OCF_SUCCESS ]] ; then
-                    ocf_log err "${LH} RMQ-server app can't be stopped on post-demote. Master resource is failed"
-                    exit $OCF_FAILED_MASTER
-                fi
                 ;;
             *)  ;;
         esac
