Check if the rabbitmqctl command is responding
W/o this fix, rabbitmqctl sometimes may hang failing
many commands. This is a problem as it brings the rabbit node
to unresponsive and broken state. This also may affect
entire cluster operations, for example, when the failed command is
the forget_cluster_node.

The solution is to check for the cases when the command rabbitmqctl
list_channels timed out and killed or termintated with exit codes
137 or 124 and return generic error.
There is also related confusing error message "get_status() returns generic
error" may be logged when the rabbit node is running out of the cluster
and fixed as well.

Closes-bug: #1459173

Change-Id: Ia52fc5f2ab7adb36252a7194f9209ab87ce487de
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/files/fuel-ha-utils/ocf/rabbitmq b/files/fuel-ha-utils/ocf/rabbitmq
--- a/files/fuel-ha-utils/ocf/rabbitmq
+++ b/files/fuel-ha-utils/ocf/rabbitmq
@@ -977,7 +977,7 @@ get_monitor() {
     local status_master
     local rabbit_running
     local nodelist
-    local prev_rc
+    local rc2=$OCF_SUCCESS
     local max
     local our_uptime
     local node_uptime
@@ -1010,7 +1010,6 @@ get_monitor() {
     if [ $rabbit_running == $OCF_SUCCESS ]
         then
             ocf_log info "${LH} rabbit app is running. checking if we are the part of healthy cluster"
-            prev_rc=$rc
             nodelist=$(get_alive_pacemaker_nodes_but)
             for node in $nodelist
             do
@@ -1019,20 +1018,20 @@ get_monitor() {
                 status_master=$?
                 ocf_log info "${LH} fetched master attribute for $node. attr value is ${status_master}"
                 if [ $status_master -eq 0 ] ; then
-                    rc=$OCF_ERR_GENERIC
+                    rc2=$OCF_ERR_GENERIC
                     ocf_log info "${LH} rabbit app is running. master is $node"
                     if get_running_nodes | grep -q $(rabbit_node_name $node)
                     then
                         ocf_log info "${LH} rabbit app is running and is member of healthy cluster"
-                        rc=$prev_rc
                         break
                     fi
                 fi
             done
+            [ $rc2 -ne $OCF_ERR_GENERIC ] || ocf_log err "${LH} rabbit app is running out of the cluster"
     fi
 
     if [[ $rc == $OCF_ERR_GENERIC ]]; then
-        ocf_log info "${LH} get_status() returns generic error ${rc}"
+        ocf_log err "${LH} get_status() returns generic error ${rc}"
         ocf_log info "${LH} ensuring this slave does not get promoted."
         master_score 0
         return $OCF_ERR_GENERIC
@@ -1074,6 +1073,17 @@ get_monitor() {
             ocf_log info "${LH} we are the oldest node"
             master_score 1000
         fi
+    fi
+
+    # Check if the rabbitmqctl control plane is alive.
+    # The rabbit app may be not running and the command
+    # will return > 0, so we only check if the command execution
+    # has timed out (which is a code 137)
+    su_rabbit_cmd "${OCF_RESKEY_ctl} list_channels 2>&1 > /dev/null"
+    rc2=$?
+    if [ $rc2 -eq 137 -o $rc2 -eq 124 ]; then
+        ocf_log err "${LH} rabbitmqctl is not responding. The resource is failed."
+        return $OCF_ERR_GENERIC
     fi
     ocf_log info "${LH} get_monitor function ready to return ${rc}"
     return $rc
