Fix rabbit OCF demote/stop/promote actions
* When the rabbit node went down, its status remains 'running'
  in mnesia db for a while, so few retries (50 sec of total) are
  required in order to kick and forget this node from the cluster.
  This also requires +50 sec for actions stop & demote timeout.
* The rabbit master score in the CIB is retained after the current
  master moved manually. This is wrong and the score must be reset
  ASAP for post-demote and post-stop as well.
* The demoted node must be kicked from cluster by other nodes
  on post-demote processing.
* Post-demote should stop the rabbit app at the node being demoted as
  this node should be kicked from the cluster by other nodes.
  But it stops the app at the *other* nodes instead.
* The check to join for post-promote action should be done only
  for the slaves, while the master should not do anything on
  post-promote
  (the regression was caused by https://review.openstack.org/184671)
* Change `hostname` call to `crm_node -n` everywhere to ensure
  we are using correct pacemaker node name
* Introduce functions to get pacemaker node names:
  a) to get all alive nodes in the partition
  b) to get all nodes
  This fixes get_monitor behaviour so that it ignores
  attributes for dead nodes as crm_node behaviour
  changed with upgrade of pacemaker

Closes-bug: #1436812
Closes-bug: #1455761

Change-Id: Ib01c1731b4f06e6b643a4bca845828f7db507ad3
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/files/fuel-ha-utils/ocf/rabbitmq b/files/fuel-ha-utils/ocf/rabbitmq
--- a/files/fuel-ha-utils/ocf/rabbitmq
+++ b/files/fuel-ha-utils/ocf/rabbitmq
@@ -263,7 +263,7 @@ my_host() {
 
 srv_uptime() {
     local stime
-    stime=$( crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --query 2>/dev/null | awk '{print $3}' | awk -F "=" '{print $2}' | sed -e '/(null)/d' )
+    stime=$( crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-start-time' --query 2>/dev/null | awk '{print $3}' | awk -F "=" '{print $2}' | sed -e '/(null)/d' )
 
     if [ -z "${stime}" -o x"${stime}" == x"(null)" ] ; then
         echo 0
@@ -430,6 +430,19 @@ get_running_nodes() {
     return $?
 }
 
+
+get_all_pacemaker_nodes()
+{
+    echo `crm_node -l | awk '{print $2}' | grep -v "^$" | sed -e '/(null)/d'`
+    return $?
+}
+
+get_alive_pacemaker_nodes()
+{
+    echo $( crm_node -l -p )
+    return $?
+}
+
 check_need_join_to() {
     local join_to=$(rabbit_node_name $1)
     local node
@@ -542,7 +555,7 @@ join_to_cluster() {
         return $OCF_ERR_GENERIC
     else
         ocf_log info "${LH} Rabbit app started successfully. Updating start time attribute with $(now)"
-        ocf_run crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --update $(now)
+        ocf_run crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-start-time' --update $(now)
         ocf_log info "${LH} Joined to cluster succesfully."
     fi
 
@@ -587,13 +600,24 @@ unjoin_nodes_from_cluster() {
                 fi
 
                 # unjoin node
+                # when the rabbit node went down, its status
+                # remains 'running' for a while, so few retries are required
+                local tries=0
+                until [ $tries -eq 5 ]; do
+                    ((tries++))
+                    if get_running_nodes | grep -q $(rabbit_node_name $nodename)
+                    then
+                        ocf_log info "${LH} the ${nodename} is alive and cannot be kicked from the cluster yet"
+                    fi
+                    sleep 10
+                done
                 ocf_log info "${LH} Execute forget_cluster_node with timeout: ${TIMEOUT_ARG}"
                 su_rabbit_cmd "${OCF_RESKEY_ctl} forget_cluster_node ${nodename}"
                 rc=$?
                 if [[ $rc == 0 ]] ; then
-                    ocf_log info "${LH} node '${nodename}' unjoined succesfully."
+                   ocf_log info "${LH} node '${nodename}' unjoined succesfully."
                 else
-                    ocf_log info "${LH} unjoining node '${nodename}' failed."
+                   ocf_log warn "${LH} unjoining node '${nodename}' failed."
                 fi
             fi
         done
@@ -956,7 +980,7 @@ get_monitor() {
         ocf_log info "${LH} also checking if we are master."
         get_status rabbit
         rabbit_running=$?
-        is_master `hostname`
+        is_master `crm_node -n`
         status_master=$?
         ocf_log info "${LH} master attribute is ${status_master}"
         if [ $status_master -eq 0 -a $rabbit_running -eq $OCF_SUCCESS ]
@@ -972,7 +996,7 @@ get_monitor() {
         then
             ocf_log info "${LH} rabbit app is running. checking if we are the part of healthy cluster"
             prev_rc=$rc
-            nodelist=`crm_node -p -l | grep -v lost | awk '{print $2}' | grep -v "^$" | sed -e '/(null)/d'`
+            nodelist=$(get_alive_pacemaker_nodes)
             for node in $nodelist
             do
                 ocf_log info "${LH} rabbit app is running. looking for master on $node"
@@ -1000,7 +1024,7 @@ get_monitor() {
     else
         ocf_log info "${LH} preparing to update master score for node"
         our_uptime=$(srv_uptime)
-        nodelist=$( crm_node -p -l | grep -v lost | awk '{print $2}' | grep -v "^$" | grep -v `hostname` | sed -e '/(null)/d' )
+        nodelist=$(get_alive_pacemaker_nodes)
         max=1
         for node in $nodelist
         do
@@ -1109,13 +1133,13 @@ action_stop() {
 
     # remove master flag
     # remove master score
-    crm_attribute -N `hostname` -l reboot --name 'rabbit-master' --delete
+    crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-master' --delete
     master_score 0
 
     ocf_log info "${LH} RMQ-runtime (beam) going to down."
     stop_server_process
 
-    crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --delete
+    crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-start-time' --delete
     #  remove file with rmq-server start timestamp
 
     #todo: make this timeout corresponded to the stop timeout for resource
@@ -1180,7 +1204,7 @@ action_notify() {
                 my_host "$OCF_RESKEY_CRM_meta_notify_promote_uname"
                 rc=$?
                 if [[ $rc == $OCF_SUCCESS ]] ; then
-                    nodelist=`crm_node -l | awk '{print $2}' | grep -v "^$" | sed -e '/(null)/d'`
+                    nodelist=$(get_all_pacemaker_nodes)
                     for i in $nodelist
                     do
                        crm_attribute -N $i -l reboot --name 'rabbit-master' --delete
@@ -1198,15 +1222,22 @@ action_notify() {
         case "$OCF_RESKEY_CRM_meta_notify_operation" in
             promote)
                 ocf_log info "${LH} post-promote begin."
-                check_need_join_to ${OCF_RESKEY_CRM_meta_notify_promote_uname}
-                rc_join=$?
-                if [[ ${rc_join} == $OCF_SUCCESS ]]; then
-                  ocf_log warn "${LH} Going to join node ${OCF_RESKEY_CRM_meta_notify_promote_uname}"
-                  jjj_join ${OCF_RESKEY_CRM_meta_notify_promote_uname}
-                  rc=$?
+                my_host ${OCF_RESKEY_CRM_meta_notify_promote_uname}
+                rc=$?
+                if [[ $rc == $OCF_SUCCESS ]]; then
+                  ocf_log warn "${LH} We are the master. No need to do anything on post-promote."
+                  return $OCF_SUCCESS
                 else
-                  ocf_log warn "${LH} We are already clustered with node ${OCF_RESKEY_CRM_meta_notify_promote_uname}"
-                  rc=$OCF_SUCCESS
+                  check_need_join_to ${OCF_RESKEY_CRM_meta_notify_promote_uname}
+                  rc_join=$?
+                  if [[ $rc_join == $OCF_SUCCESS ]]; then
+                    ocf_log warn "${LH} Going to join node ${OCF_RESKEY_CRM_meta_notify_promote_uname}"
+                    jjj_join ${OCF_RESKEY_CRM_meta_notify_promote_uname}
+                    rc=$?
+                  else
+                    ocf_log warn "${LH} We are already clustered with node ${OCF_RESKEY_CRM_meta_notify_promote_uname}"
+                    rc=$OCF_SUCCESS
+                  fi
                 fi
                 ocf_log info "${LH} post-promote end."
                 if [[ $rc == $OCF_ERR_GENERIC ]] ; then
@@ -1219,6 +1250,10 @@ action_notify() {
                 # check did this event from this host
                 my_host "${OCF_RESKEY_CRM_meta_notify_start_uname} ${OCF_RESKEY_CRM_meta_notify_active_uname}"
                 rc=$?
+                if [ -z ${OCF_RESKEY_CRM_meta_notify_master_uname} ] ; then
+                  ocf_log warn "${LH} there is no master running on post-start. Resource is failed."
+                  return $OCF_NOT_RUNNING
+                fi
                 if [[ $rc == $OCF_SUCCESS ]] ; then
                     check_need_join_to ${OCF_RESKEY_CRM_meta_notify_master_uname}
                     rc_join=$?
@@ -1240,8 +1275,17 @@ action_notify() {
             stop)
                 # if rabbitmq-server stops on any another node, we should remove it from cluster (as ordinary operation)
                 ocf_log info "${LH} post-stop begin."
+                my_host "${OCF_RESKEY_CRM_meta_notify_stop_uname}"
+                rc=$?
+                if [[ $rc != $OCF_SUCCESS ]] ; then
+                    # On ohter nodes processing the post-stop, make sure the stopped node will be forgotten
+                    unjoin_nodes_from_cluster "${OCF_RESKEY_CRM_meta_notify_stop_uname}"
+                else
+                    # On the nodes being stopped, reset the master score
+                    ocf_log info "${LH} resetting the master score."
+                    master_score 0
+                fi
                 # always returns OCF_SUCCESS
-                unjoin_nodes_from_cluster "${OCF_RESKEY_CRM_meta_notify_stop_uname}"
                 ocf_log info "${LH} post-stop end."
                 ;;
             demote)
@@ -1250,16 +1294,22 @@ action_notify() {
                 my_host "${OCF_RESKEY_CRM_meta_notify_demote_uname}"
                 rc=$?
                 if [[ $rc != $OCF_SUCCESS ]] ; then
-                   ocf_log info "${LH} master was demoted. stopping RabbitMQ app."
-                   stop_rmq_server_app
-                   rc2=$?
-                   crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --delete
+                    # On ohter nodes processing the post-demote, make sure the demoted node will be forgotten
+                    unjoin_nodes_from_cluster "${OCF_RESKEY_CRM_meta_notify_demote_uname}"
+                else
+                    # On the nodes being demoted, reset the master score
+                    ocf_log info "${LH} resetting the master score."
+                    master_score 0
+                    ocf_log info "${LH} master was demoted. stopping RabbitMQ app."
+                    stop_rmq_server_app
+                    rc2=$?
+                    crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-start-time' --delete
+                    if [[ $rc2 != $OCF_SUCCESS ]] ; then
+                        ocf_log err "${LH} RMQ-server app can't be stopped on post-demote. Master resource is failed"
+                        exit $OCF_FAILED_MASTER
+                    fi
                 fi
                 ocf_log info "${LH} post-demote end."
-                if [[ $rc2 != $OCF_SUCCESS ]] ; then
-                    ocf_log err "${LH} RMQ-server app can't be stopped on post-demote. Master resource is failed"
-                    exit $OCF_FAILED_MASTER
-                fi
                 ;;
             *)  ;;
         esac
@@ -1294,7 +1344,7 @@ action_promote() {
             get_status rabbit
             rc=$?
             ocf_log info "${LH} Updating cluster master attribute"
-            ocf_run crm_attribute -N `hostname` -l reboot --name 'rabbit-master' --update 'true'
+            ocf_run crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-master' --update 'true'
             if [[ $rc != $OCF_SUCCESS ]] ; then
                 ocf_log info "${LH} RMQ app is not started. Starting..."
                 start_rmq_server_app
@@ -1314,7 +1364,7 @@ action_promote() {
                     rabbitmqctl set_policy tasks_expire "^tasks\\." '{"expires":3600000,"ha-mode":"all","ha-sync-mode":"automatic"}' --apply-to all --priority 1
                     # create timestamp file
                     ocf_log info "${LH} Updating start timestamp"
-                    ocf_run crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --update $(now)
+                    ocf_run crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-start-time' --update $(now)
                     ocf_log info "${LH} Checking master status"
                     get_monitor
                     rc=$?
@@ -1390,8 +1440,8 @@ action_demote() {
             ocf_log warn "${LH} Resource is currently running as Master"
             stop_rmq_server_app
             rc=$?
-            crm_attribute -N `hostname` -l reboot --name 'rabbit-master' --delete
-            crm_attribute -N `hostname` -l reboot --name 'rabbit-start-time' --delete
+            crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-master' --delete
+            crm_attribute -N `crm_node -n` -l reboot --name 'rabbit-start-time' --delete
             ;;
         "$OCF_SUCCESS")
             # Alread running as slave. Nothing to do.
