Do lazy start attempts of the rabbit app
W/o this patch, the rabbitmq app may remain joined cluster
but not started and keep running without being noticed by
OCF logic. But by design, the app is supposed to be stopped for
some cases and monitor action should not treat this state
as en error.

This is a problem as we don't want permanent states with
the rabbit app retained stopped because in this state the
rabbit node cannot process AMQP at all. Besides that,
we also want the rabbit app to be ready ASAP, but w/o some
"lazy start" attempts, the unavailability window only increases.

The solution is to make the rabbit app at least have tried
to start (a lazy start attempt) in the end of monitor
and post-promote and ignore results because it is normal
when it cannot start for some transient cluster states.
And at the post-start, also check if the rabbit app can be
started and report the resource as not running, if it cannot.
This will ensure eventual readiness of the rabbitmq app in the
stop-start loop along with minimizing its downtime.

Closes-bug: #1455761

Change-Id: Iffdb53860a4b53b0f7b6b1798aeb8088e7bc542c
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/files/fuel-ha-utils/ocf/rabbitmq b/files/fuel-ha-utils/ocf/rabbitmq
--- a/files/fuel-ha-utils/ocf/rabbitmq
+++ b/files/fuel-ha-utils/ocf/rabbitmq
@@ -431,6 +431,16 @@ get_running_nodes() {
     return $?
 }
 
+start_app_maybe() {
+  local LH="${LL} start_app_maybe():"
+  su_rabbit_cmd "${OCF_RESKEY_ctl} start_app >>${startup_log} 2>&1"
+  local rc=$?
+  ocf_log info "${LH} The lazy start attempt for the rabbitmq app returned ${rc}"
+  return $rc
+}
+
+# Check if the given node has to join the cluster
+# Return 0, if it has to, otherwise return 1
 check_need_join_to() {
     local join_to=$(rabbit_node_name $1)
     local node
@@ -792,7 +802,10 @@ try_to_start_rmq_app() {
 
     ocf_log info "${LH} begin."
     ocf_log info "${LH} Execute start_app with timeout: ${TIMEOUT_ARG}"
-    su_rabbit_cmd "${OCF_RESKEY_ctl} start_app >>${startup_log} 2>&1"
+    # Do a lazy start attempt
+    # If the rabbit app cannot start, it is ok as it may be not ready yet.
+    start_app_maybe
+    ocf_log info "${LH} The lazy start attempt result is OK anyway"
     rc=$?
     if [[ $rc == 0 ]] ; then
         ocf_log info "${LH} start_app was successful."
@@ -1048,6 +1061,10 @@ get_monitor() {
             master_score 1000
         fi
     fi
+    # Do a lazy start attempt
+    # If the rabbit app cannot start, it is ok as it may be not ready yet.
+    start_app_maybe
+    ocf_log info "${LH} The lazy start attempt result is OK anyway"
     ocf_log info "${LH} get_monitor function ready to return ${rc}"
     return $rc
 }
@@ -1221,6 +1238,10 @@ action_notify() {
                 # Later this ex-master node will rejoin the cluster at post-start.
                 jjj_join ${OCF_RESKEY_CRM_meta_notify_promote_uname}
                 rc=$?
+                # Do a lazy start attempt
+                # If the rabbit app cannot start, it is ok as it may be not ready yet.
+                start_app_maybe
+                ocf_log info "${LH} The lazy start attempt result is OK anyway"
                 ocf_log info "${LH} post-promote end."
                 if [[ $rc == $OCF_ERR_GENERIC ]] ; then
                     ocf_log err "${LH} Failed to join the cluster on post-promote. The resource will be restarted."
@@ -1256,9 +1277,13 @@ action_notify() {
                       ocf_log warn "${LH} We are already clustered with node ${OCF_RESKEY_CRM_meta_notify_master_uname}"
                       rc2=$OCF_SUCCESS
                     fi
+                    # If the rabbit app cannot start here, report the resource as not running
+                    start_app_maybe
+                    local rc_started=$?
+                    [ $rc_started -eq 0 ] || ocf_log warn "${LH} The lazy start attempt result was expected to be successfull, but failed"
                     ocf_log info "${LH} post-start end."
-                    if [[ $rc2 == $OCF_ERR_GENERIC ]] ; then
-                        ocf_log warn "${LH} Failed to join the cluster on post-start. The resource will be restarted."
+                    if [ $rc2 -eq $OCF_ERR_GENERIC -o $rc_started -ne 0 ] ; then
+                        ocf_log warn "${LH} Failed to join the cluster and start rabbit app on post-start. The resource will be restarted."
                         ocf_log info "${LH} post-start end."
                         return $OCF_NOT_RUNNING
                     fi
