Refactor the stop operation for neutron-dhcp-agent
* Combine the stopping of neutron-dhcp-agent and the stopping of dnsmasq
processes inside namespaces into one time period (it was only for stopping
of ONE neutron dhcp process).
* Clean up duplicate code .

Change-Id: Iaaa2b6f7c8e3b0fa870715c69fd39fa45e5dc526
Closes-Bug: 1377906

diff --git a/deployment/puppet/cluster/files/ocf/neutron-agent-dhcp b/deployment/puppet/cluster/files/ocf/neutron-agent-dhcp
--- a/deployment/puppet/cluster/files/ocf/neutron-agent-dhcp
+++ b/deployment/puppet/cluster/files/ocf/neutron-agent-dhcp
@@ -106,9 +106,9 @@ creates a distributed neutron-dhcp-agent cluster.
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack DHCP Server server binary (${OCF_RESKEY_binary})
+Location of the OpenStack DHCP Agent server binary (${OCF_RESKEY_binary})
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server server binary (${OCF_RESKEY_binary})</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Agent server binary (${OCF_RESKEY_binary})</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
@@ -116,7 +116,7 @@ Location of the OpenStack DHCP Server server binary (${OCF_RESKEY_binary})
 <longdesc lang="en">
 Location of the OpenStack Neutron Service (neutron-server) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (neutron-server) config file</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Agent (neutron-server) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
@@ -132,7 +132,7 @@ Location of the Keystone configuration file
 <longdesc lang="en">
 Location of the OpenStack DHCP Service (${OCF_RESKEY_binary}) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (${OCF_RESKEY_binary}) config file</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Agent (${OCF_RESKEY_binary}) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_plugin_config_default}" />
 </parameter>
 
@@ -363,11 +363,9 @@ clean_up() {
         if [ -z "$inside_ns_pids" ] ; then
             break
         fi
-        for ns_pid in $inside_ns_pids ; do
-          ocf_run kill $ns_pid
-        done
+        ocf_run kill $inside_ns_pids
         sleep 1
-        count=$(($count - 1))
+        ((count--))
     done
 
     # kill all remaining proceses, that not died by simple kill
@@ -415,11 +413,11 @@ neutron_dhcp_agent_monitor() {
     network_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
     rc=$?
     if [ $rc -ne 0 ]; then
-      ocf_log err "Neutron DHCP Server is not connected to the AMQP server : $rc"
+      ocf_log err "Neutron DHCP Agent is not connected to the AMQP server : $rc"
       return $OCF_NOT_RUNNING
     fi
 
-    ocf_log debug "OpenStack DHCP Server (neutron-dhcp-agent) monitor succeeded"
+    ocf_log debug "OpenStack DHCP Agent (neutron-dhcp-agent) monitor succeeded"
     return $OCF_SUCCESS
 }
 
@@ -429,7 +427,7 @@ neutron_dhcp_agent_start() {
     neutron_dhcp_agent_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) already running"
+        ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) already running"
         return $OCF_SUCCESS
     fi
 
@@ -449,7 +447,7 @@ neutron_dhcp_agent_start() {
         rc=$?
         [ $rc -eq $OCF_SUCCESS ] && break
         if [ $rc -ne $OCF_NOT_RUNNING ]; then
-            ocf_log err "OpenStack DHCP Server (${OCF_RESKEY_binary}) start failed"
+            ocf_log err "OpenStack DHCP Agent (${OCF_RESKEY_binary}) start failed"
             exit $OCF_ERR_GENERIC
         fi
         sleep 3
@@ -465,7 +463,7 @@ neutron_dhcp_agent_start() {
         bash -c "$RESCH_CMD" &
     fi
 
-    ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) started"
+    ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) started"
     return $OCF_SUCCESS
 }
 
@@ -478,7 +476,7 @@ neutron_dhcp_agent_stop() {
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
         clean_up
-        ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) already stopped"
+        ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) already stopped"
         sleep 1
         clean_up_namespaces
         return $OCF_SUCCESS
@@ -486,49 +484,58 @@ neutron_dhcp_agent_stop() {
 
     #Try SIGTERM
     pid=`get_worker_pid`
-    if [ "xxx$pid" == "xxx" ] ; then
-        ocf_log warn "OpenStack DHCP Server (${OCF_RESKEY_binary}) not running."
-        #return $OCF_NOT_RUNNING
-        return $OCF_SUCCESS
-    fi
-    ocf_run kill -s TERM $pid
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack DHCP Server (${OCF_RESKEY_binary}) couldn't be stopped"
-        exit $OCF_ERR_GENERIC
-    fi
-
     # stop waiting
     shutdown_timeout=15
+    iteration_time=3
     if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
-        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
+        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-6))
     fi
+    all_inside_ns_pids=`get_pid_list_for_ns_list $(get_ns_list)`
+    all_pids="$pid $all_inside_ns_pids"
     count=0
-    while [ $count -lt $shutdown_timeout ]; do
-        neutron_dhcp_agent_status
-        rc=$?
-        if [ $rc -eq $OCF_NOT_RUNNING ]; then
-            break
+    alive=1
+    while [ $alive -gt 0 ] && [ $count -lt $shutdown_timeout ]; do
+        alive=0
+        ocf_run kill -s TERM $all_pids
+        sleep $iteration_time
+        #Check if processes are alive after command kill
+        #if yes, send to them the term signal again
+        np=""
+        for pid in $all_pids ; do
+            ocf_run kill -s 0 $pid
+            if [ $? -eq 0 ]; then
+                np="$np $pid"
+                ((alive++))
+            fi
+        done
+        if [ $alive -gt 0 ] ; then
+            all_pids=$np
         fi
-        count=`expr $count + 1`
-        sleep 1
-        ocf_log debug "OpenStack DHCP Server (${OCF_RESKEY_binary}) still hasn't stopped yet. Waiting ..."
+        ((count+=$iteration_time))
+        ocf_log debug "OpenStack DHCP Agent (${OCF_RESKEY_binary}) still hasn't stopped yet. Waiting ..."
     done
-
-    neutron_dhcp_agent_status
-    rc=$?
-    if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) failed to stop after ${shutdown_timeout}s \
-          using SIGTERM. Trying SIGKILL ..."
-        ocf_run kill -s KILL $pid
+    #Send the kill signal to processes which are still alive
+    if [ $alive -gt 0 ] ; then
+        alive=0
+        ocf_run kill -s KILL $all_pids
+        sleep 1
+        for pid in $all_pids ; do
+            ocf_run kill -s 0 $pid
+            if [ $? -eq 0 ]; then
+                ((alive++))
+            fi
+        done
+        if [ $alive -gt 0 ] ; then
+            ocf_log err "OpenStack DHCP Agent (${OCF_RESKEY_binary}) stop failed"
+            return $OCF_ERR_GENERIC
+        fi
     fi
-    ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) stopped"
+    ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) stopped"
 
     rm -f $OCF_RESKEY_pid
 
-    clean_up
-    sleep 1
+#   cleanup network interfaces
+    q-agent-cleanup.py --agent=dhcp --cleanup-ports
     clean_up_namespaces
     if ! ocf_is_true "$OCF_RESKEY_multiple_agents" ; then
         q-agent-cleanup.py --agent=dhcp --remove-self ${AUTH_TAIL} 2>&1 >> /var/log/neutron/rescheduling.log &
