Add inspect subcommand to dockerctl
Take this opportunity to replace bunch of if conditionals with the case
statement.

Change-Id: Ic0c80c3fadb607d4f8356adf7f77fe671328477d
Closes-bug: 1400776

diff --git a/files/fuel-docker-utils/dockerctl b/files/fuel-docker-utils/dockerctl
--- a/files/fuel-docker-utils/dockerctl
+++ b/files/fuel-docker-utils/dockerctl
@@ -39,83 +39,66 @@ fi
 
 container_seq=$CONTAINER_SEQUENCE
 
-if [ "$1" == "build" ]; then
-  if [ "$container" = "storage" ]; then
-    build_storage_containers
-    run_storage_containers
-  elif [ "$container" = "all" ];then
-    #Step 1: prepare storage containers
-    build_storage_containers
-    run_storage_containers
+case "$1" in
+  build)
+    if [[ "$container" == 'storage' ]]; then
+      build_storage_containers
+      run_storage_containers
+    elif [[ "$container" == 'all' ]]; then
+      # Step 1: prepare storage containers
+      build_storage_containers
+      run_storage_containers
 
-    #Step 2: Launch all in order, checking each one
-    for service in $container_seq; do
-      start_container $service
-      check_ready $service
-    done
-  else
-    start_container $container
-  fi
-elif [ "$1" == "start" ]; then
-  if [ "$container" = "all" ];then
-    for service in $container_seq; do
-      start_container $service
-      check_ready $service
-      sleep 4
-    done
-  else
-    shift 2
-    start_container $container $@
-    if ! [[ "$@" =~ "--attach" ]]; then
+      # Step 2: launch all in order, checking each one
+      for service in $container_seq; do
+        start_container $service
+        check_ready $service
+      done
+    else
+      start_container $container
+    fi ;;
+  check)
+    if [[ "$container" == 'all' ]];then
+      exit_code=0
+      for service in $container_seq; do
+        check_ready $service || exit_code=1
+      done
+      exit $exit_code
+    else
       check_ready $container
-    fi
-  fi
-elif [ "$1" == "check" ]; then
-  if [ "$container" = "all" ];then
-    exit_code=0
-    for service in $container_seq; do
-      check_ready $service || exit_code=1
-    done
-    exit $exit_code
-  else
-    check_ready $container
-  fi
-elif [ "$1" == "list" ]; then
-  shift 1
-  list_containers "$@"
-elif [ "$1" == "copy" ]; then
-  shift 1
-  copy_files "$@"
-elif [ "$1" == "restart" ]; then
-  shift 2
-  restart_container $container $@
-elif [ "$1" == "stop" ]; then
-  shift 2
-  stop_container $container $@
-elif [ "$1" == "revert" ]; then
-  shift 2
-  revert_container $container $@
-elif [ "$1" == "shell" ]; then
-  shift 2
-  shell_container $container "$@"
-elif [ "$1" == "upgrade" ]; then
-  shift 2
-  upgrade_container $container $@
-elif [ "$1" == "restore" ]; then
-  shift
-  restore "$@"
-elif [ "$1" == "backup" ]; then
-  shift
-  backup "$@"
-elif [ "$1" == "destroy" ]; then
-  shift 2
-  destroy_container $container $@
-elif [ "$1" == "logs" ]; then
-  logs $container
-elif [ "$1" == "post_start_hooks" ]; then
-  shift 2
-  post_start_hooks "$container" "$@"
-else
-  echo "Invalid selection."
-  show_usage
-fi
+    fi ;;
+  start)
+    if [[ "$container" == 'all' ]]; then
+      for service in $container_seq; do
+        start_container $service
+        check_ready $service
+        sleep 4
+      done
+    else
+      shift 2
+      start_container $container $@
+      if [[ ! "$@" =~ "--attach" ]]; then
+        check_ready $container
+      fi
+    fi ;;
+  post_start_hooks)
+    shift 2
+    post_start_hooks $container $@ ;;
+  list)
+    shift
+    list_containers "$@" ;;
+  restart|stop|revert|shell|destroy)
+    cmd=$1
+    shift 2
+    ${cmd}_container $container $@ ;;
+  restore|backup)
+    cmd=$1
+    shift
+    $cmd "$@" ;;
+  logs|inspect)
+    cmd=$1
+    $cmd $container ;;
+  *)
+    echo 'Invalid selection.'
+    show_usage
+esac
