Run docker containers with host networking
Note: Requires Docker 1.2 or greater.

This change removes the need for dhcrelay
for cobbler container and the configuration
of masquerade ip forward rules. It will be
left installed in case of rollback to a
previous Fuel release.

Changes LXC driver to native exec driver
libcontainer. shell command now uses docker
exec command instead of lxc-attach.

Added privileged mode to nailgun container which
is necessary for sysctl to operate with host
networking mode.

blueprint fuel-master-docker-host-networking
blueprint fuel-master-docker-upgrade

Change-Id: I4111caf9ac7b33c514481704b3fb253966759748
Fuel-CI: disable

diff --git a/deployment/puppet/docker/templates/functions.sh.erb b/deployment/puppet/docker/templates/functions.sh.erb
--- a/deployment/puppet/docker/templates/functions.sh.erb
+++ b/deployment/puppet/docker/templates/functions.sh.erb
@@ -248,8 +248,8 @@ function shutdown_container {
 }
 
 function attach_container {
-  echo "Attaching to container $container_name..."
-  ${DOCKER} attach $1 &
+  echo "Attaching to container $1..."
+  ${DOCKER} attach --no-stdin $1 &
   APID=$!
   trap "shutdown_container $1 $APID" INT TERM
   while test -d "/proc/$APID/fd" ; do
@@ -258,6 +258,40 @@ function attach_container {
 }
 
 function shell_container {
+  case $EXEC_DRIVER in
+    lxc)  lxc_shell_container "$@"
+          ;;
+    *)    exec_shell_container "$@"
+  esac
+}
+
+function exec_shell_container {
+  exec_opts=''
+  #Interactive shell only if we have TTY
+  if [ -t 0 ]; then
+    exec_opts+=' -i'
+  fi
+  if [ -t 1 ]; then
+    exec_opts+=' -t'
+  fi
+  id=$(get_container_id "$1")
+  if [ $? -ne 0 ]; then
+    echo "Could not get docker ID for $container. Is it running?" 1>&2
+    return 1
+  fi
+  #TODO(mattymo): fix UTF-8 bash warning
+  #Setting C locale to suppress bash warning
+  prefix="env LANG=C"
+  if [ -z "$2" ]; then
+    command="/bin/bash"
+  else
+    shift
+    command=("$@")
+  fi
+  docker exec $exec_opts $id $prefix "${command[@]}"
+}
+
+function lxc_shell_container {
   id=$(get_container_id "$1")
   if [ $? -ne 0 ]; then
     echo "Could not get docker ID for $container. Is it running?" 1>&2
@@ -377,131 +411,14 @@ function pre_start_hooks {
 }
 
 function post_setup_hooks {
-  purge_stale_iptables_rules $1
   case $1 in
-    cobbler)   setup_dhcrelay_for_cobbler
-               ;;
-    rsyslog)   remangle_syslog
-               ;;
-    nginx)     remangle_nginx
-               ;;
     *)         ;;
   esac
 }
 function post_start_hooks {
-  purge_stale_iptables_rules $1
   case $1 in
-    cobbler)   setup_dhcrelay_for_cobbler
-               ;;
-    nginx)     remangle_nginx
-               ;;
-    rsyslog)   remangle_syslog
-               ;;
     *)         ;;
   esac
-}
-function remangle_port {
-  container=$1
-  proto=$2
-  port=$3
-  admin_interface=$(grep interface: $ASTUTE_YAML | cut -d':' -f2 | tr -d ' ')
-  #Use facter and ipcalc to get admin network CIDR
-  admin_net_ip=$(facter "ipaddress_${admin_interface}")
-  admin_net_netmask=$(facter "netmask_$admin_interface")
-  eval $(ipcalc -np "$admin_net_ip" "$admin_net_netmask")
-  #purge old rule
-  purge_iptables_rule "$container-$proto-$port-accept"
-  purge_iptables_rule "$container-$proto-$port-unmasquerade"
-
-  iptables -t nat -I POSTROUTING 1 -s "$NETWORK/$PREFIX" -p $proto -m $proto --dport $port -m comment --comment "$container-$proto-$port-unmasquerade" -j ACCEPT
-  iptables -A FORWARD -i $admin_interface -o docker0 -m state --state NEW -p $proto  -m $proto --dport $port -m comment --comment "$container-$proto-$port-accept" -j ACCEPT
-  service iptables save &>/dev/null
-}
-function purge_stale_iptables_rules {
-  container=$1
-  containername=${CONTAINER_NAMES[$container]}
-  ports=$(docker inspect --format='{{ range $key, $value := .NetworkSettings.Ports }}{{ $key }} {{ end }}' $containername)
-  containerip=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' $containername)
-
-  for portproto in $ports; do
-    port=$(echo $portproto | cut -d'/' -f1)
-    proto=$(echo $portproto | cut -d'/' -f2)
-      while read rule; do
-        #if rule ips do not contain $containerip, drop it
-        ruleips=$(echo $rule | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])')
-        if ! [[ "$ruleips" =~ "$containerip" ]]; then
-          iptables-save | grep -v -- "$rule" | iptables-restore
-        fi
-      done < <(iptables-save | grep -- "-m $proto --dport $port")
-  done
-}
-
-function purge_iptables_rule {
-  comment="$1"
-  #method="deleteandsave"
-  method="savegreprestore"
-
-  if [ -z "$1" ]; then
-    echo "Error: No rule to match!" 1>&2
-    exit 1
-  fi
-
-  if [[ "$method" == "deleteandsave" ]];then
-    #Purge rules in filter table
-    for chain in INPUT FORWARD; do
-      while read lineno _; do
-        iptables -D $chain $lineno
-        service iptables save &>/dev/null
-      done < <(iptables -t filter --line-numbers -L $chain | grep -- "/\* ${comment} \*/")
-    done
-
-    #Purge rules in nat table
-    for chain in POSTROUTING; do
-      while read lineno _; do
-        iptables -D $chain $lineno
-        service iptables save &>/dev/null
-      done < <(iptables -t nat --line-numbers -L $chain | grep -- "/\* ${comment} \*/")
-    done
-  elif [[ "$method" == "savegreprestore" ]]; then
-    iptables-save | grep -v -- "$comment" | iptables-restore
-    service iptables save &>/dev/null
-  fi
-}
-
-function remangle_nginx {
-  #Necessary to forward packets to rsyslog with correct src ip
-  remangle_port nginx tcp 8000
-  remangle_port nginx tcp 8080
-}
-
-function remangle_syslog {
-  #Necessary to forward packets to rsyslog with correct src ip
-  remangle_port rsyslog tcp 514
-  remangle_port rsyslog udp 514
-}
-
-function setup_dhcrelay_for_cobbler {
-  if ! is_running "cobbler"; then
-    echo "ERROR: Cobbler container isn't running." 1>&2
-    exit 1
-  fi
-  cobbler_ip=$(${DOCKER} inspect --format='{{.NetworkSettings.IPAddress}}' ${CONTAINER_NAMES["cobbler"]})
-  admin_interface=$(grep interface: $ASTUTE_YAML | cut -d':' -f2 | tr -d ' ')
-  cat > /etc/sysconfig/dhcrelay << EOF
-# Command line options here
-DHCRELAYARGS=""
-# DHCPv4 only
-INTERFACES="$admin_interface docker0"
-# DHCPv4 only
-DHCPSERVERS="$cobbler_ip"
-EOF
-  rpm -q dhcp 2>&1 > /dev/null || yum --quiet -y install dhcp
-  chkconfig dhcrelay on
-  service dhcrelay restart
-}
-
-function allow_all_docker_traffic {
-  iptables -A POSTROUTING -t nat  -o docker0  -j MASQUERADE
 }
 
 function container_root {
