Improve backup restore feature
Fix system dirs restore
Enable better checking for errors
More verbose output
Added rsync destination for backup

blueprint backup-master-node

Change-Id: Ic7fac5705af4bb360d52edfe37253ea679300353

diff --git a/deployment/puppet/docker/templates/functions.sh.erb b/deployment/puppet/docker/templates/functions.sh.erb
--- a/deployment/puppet/docker/templates/functions.sh.erb
+++ b/deployment/puppet/docker/templates/functions.sh.erb
@@ -502,22 +502,47 @@ function copy_files {
 
 function backup {
   backup_id=$(date +%F_%H%S)
+  backup_dir=$(parse_backup_dir $1)
   backup_dir="${BACKUP_ROOT}/backup_${backup_id}"
   backup_containers "$backup_id"
   backup_system_dirs
-  backup_compress
+  backup_compress "$rsync_dest"
+  [ "$use_rsync" -eq 1 ] && backup_rsync_upload $rsync_dest $backup_dir
   backup_cleanup $backup_dir
   echo "Backup complete. File is available at $backup_dir/fuel_backup${image_suffix}.tar.lrz"
   #TODO(mattymo): backup_upload backupfile
 }
+
+function parse_backup_dir {
+  use_rsync=0
+  if [ -z "$1" ]; then
+    #Default backup dir
+    echo "${BACKUP_ROOT}/backup_${backup_id}"
+  elif [ -d "$1" ]; then
+    #User defined dir exists, so use it
+    echo "$1"
+  elif [[ "$1" =~ .:. ]]; then
+    #Remote rsync dir
+    use_rsync=1
+    echo "${BACKUP_ROOT}/backup_${backup_id}"
+    rsync_dest="$1"
+  else
+    echo "Unrecognized backup destination. Valid options include:" 1>&2
+    echo "  (blank)           - backup to $BACKUP_ROOT" 1>&2
+    echo "  /path/to/backup   - local backup directory" 1>&2
+    echo "  user@server:/path - backup using rsync to server" 1>&2
+    exit 1
+  fi
+}
+
 function backup_containers {
 #Backs up all containers, regardless of being related to Fuel
 
   image_suffix="_$1"
   purge_images=0
 
-  #rm -rf "$backup_dir"
-  mkdir -p $system_dirs $backup_dir
+  [ $purge_images -eq 0 ] && rm -rf "$backup_dir"
+  mkdir -p $SYSTEM_DIRS $backup_dir
   echo "Reading container data..."
   while read containerid; do
     container_name="$(${DOCKER} inspect -f='{{.Name}}' $containerid | tr -d '/')"
@@ -534,7 +559,7 @@ function backup_containers {
 
 function backup_system_dirs {
   echo "Archiving system folders"
-  tar cf $backup_dir/system-dirs.tar -C / $system_dirs
+  tar cf $backup_dir/system-dirs.tar -C / $SYSTEM_DIRS
 }
 
 function backup_compress {
@@ -548,15 +573,48 @@ function backup_compress {
     lrzopts="-L2"
   fi
   lrzip $lrzopts "$backup_dir/fuel_backup${image_suffix}.tar" -o "$backup_dir/fuel_backup${image_suffix}.tar.lrz"
-  
+
 }
+
+function backup_rsync_upload {
+  dest="$1"
+  backup_dir="$2"
+  echo "Starting rsync backup. You may be prompted for a login."
+  rsync -vP $backup_dir/*.tar.lrz "$dest"
+  
+
+backup_rsync_upload $rsync_dest $backup_dir  
+
 function backup_cleanup {
   echo "Cleaning up..."
   [ -d "$1" ] && rm -f $1/*.tar
 }
 
 function restore {
-  restore_images $1
+#TODO(mattymo): Optionally not include system dirs during restore
+#TODO(mattymo): support remote file such as ssh://user@myhost/backup.tar.lrz
+#               or http://myhost/backup.tar.lrz
+  backupfile=$1
+  if [ -z "$backupfile" ]; then
+    #TODO(mattymo): Parse BACKUP_DIR for lrz files
+    echo "Specify a backup file to restore" 1>&2
+    exit 1
+  elif ! [ -f "$backufile" ]; then
+    echo "Archive does not exist: $backupfile" 1>&2
+    exit 1
+  elif ! [[ "$backupfile" =~ lrz$ ]]; then
+    echo "Archive does not have lrz extension." 1>&2
+    exit 2
+  fi
+  timestamp=$(echo $backupfile | sed -e 's/.*\(\d{4}-\d{2}-\d{2}_\d{4}\).*/\1/')
+  if [ -z "$timestamp" ]; then
+    echo "Unable to parse timestamp in archive." 1>&2
+    exit 3
+  fi
+  restoredir="$BACKUP_ROOT/restore-$timestamp/"
+  unpack_archive "$backupfile" "$restoredir"
+  restore_images "$restoredir"
+  restore_systemdirs "$restoredir"
   echo "Stopping and destroying existing containers..."
   destroy_container all
   echo "Preparing storage containers..."
@@ -564,27 +622,26 @@ function restore {
   echo "Starting application containers..."
   start_container all
 }
-function restore_images {
-#TODO(mattymo): specify filename or parse BACKUP_DIR for lrz files
-#TODO(mattymo): support remote file such as ssh://user@myhost/backup.tar.lrz
-#               or http://myhost/backup.tar.lrz
+
+function unpack_archive {
 #feedback as everything restores
-  if [ -z "$1" ]; then
-    echo "Specify a backup file to restore" 1>&2
-    exit 1
-  elif ! [ -f "$1" ]; then
-    echo "Archive does not exist: $1" 1>&2
-    exit 1
-  fi
-  backupfile=$1
-  timestamp=$(echo $backupfile | sed -e 's/.*\(\d{4}-\d{2}-\d{2}_\d{4}\).*/\1/')
-  restoredir=$BACKUP_ROOT/restore-$timestamp/
+  backupfile="$1"
+  restoredir="$2"
   mkdir -p "$restoredir"
   lrzip -d -o "$restoredir/fuel-backup.tar" $backupfile
-  tar -xf fuel-backup.tar -C "$restoredir" && rm -f "$restoredir/fuel-images.tar"
+  tar -xf fuel_backup.tar -C "$restoredir" && rm -f "$restoredir/fuel_backup.tar"
+}
+
+function restore_images {
+  restoredir="$1"
   for imgfile in $restoredir/*.tar; do
     echo "Loading $imgfile..."
     ${DOCKER} load -i $imgfile
     rm -f $imgfile
   done
+}
+
+function restore_systemdirs {
+  restoredir="$1"
+  tar xzf $restoredir/system-dirs.tar -C /
 }
