Fail backup on docker backup/restore error
Change-Id: I2be9d281f9a22bf1fed8dc9739d8fc2c68cbcc0b
Closes-Bug: #1428982

diff --git a/deployment/puppet/docker/templates/functions.sh.erb b/deployment/puppet/docker/templates/functions.sh.erb
--- a/deployment/puppet/docker/templates/functions.sh.erb
+++ b/deployment/puppet/docker/templates/functions.sh.erb
@@ -488,6 +488,8 @@ function copy_files {
 }
 
 function backup {
+  set -e
+  trap backup_fail EXIT
   backup_id=$(date +%F_%H%S)
   use_rsync=0
   #Sets backup_dir
@@ -504,6 +506,11 @@ finish or cancel them." 1>&2
   [ $use_rsync -eq 1 ] && backup_rsync_upload $rsync_dest $backup_dir
   backup_cleanup $backup_dir
   echo "Backup complete. File is available at $backup_dir/fuel_backup${image_suffix}.tar.lrz"
+}
+
+function backup_fail {
+  echo "Backup failed!" 1>&2
+  exit 1
 }
 
 function parse_backup_dir {
@@ -596,6 +603,8 @@ function restore {
 #TODO(mattymo): Optionally not include system dirs during restore
 #TODO(mattymo): support remote file such as ssh://user@myhost/backup.tar.lrz
 #               or http://myhost/backup.tar.lrz
+  set -e
+  trap restore_fail EXIT
   if check_nailgun_tasks; then
     echo "There are currently running Fuel tasks. Please wait for them to \
 finish or cancel them. Run \"fuel task list\" for more details." 1>&2
@@ -635,6 +644,11 @@ finish or cancel them. Run \"fuel task list\" for more details." 1>&2
   for container in $CONTAINER_SEQUENCE; do
     check_ready $container
   done
+}
+
+function restore_fail {
+  echo "Restore failed!" 1>&2
+  exit 1
 }
 
 function unpack_archive {
