Clean up iptables rules when starting containers
Purges iptables rules generated by dockerctl and
by docker itself when a container is started. It
drops existing rules created from dockerctl,
identified by comment and docker forwarding rules
based on IP address matching.

Closes-Bug: #1331807

Change-Id: I9c803d6dbeb8a341b811acbaf36e9777d40df5cc

diff --git a/deployment/puppet/docker/templates/functions.sh.erb b/deployment/puppet/docker/templates/functions.sh.erb
--- a/deployment/puppet/docker/templates/functions.sh.erb
+++ b/deployment/puppet/docker/templates/functions.sh.erb
@@ -389,6 +389,7 @@ function post_setup_hooks {
   esac
 }
 function post_start_hooks {
+  purge_stale_iptables_rules $1
   case $1 in
     cobbler)   setup_dhcrelay_for_cobbler
                ;;
@@ -396,28 +397,84 @@ function post_start_hooks {
   esac
 }
 function remangle_port {
-  proto=$1
-  port=$2
+  container=$1
+  proto=$2
+  port=$3
   admin_interface=$(grep interface: $ASTUTE_YAML | cut -d':' -f2 | tr -d ' ')
   #Use facter and ipcalc to get admin network CIDR
   admin_net_ip=$(facter "ipaddress_${admin_interface}")
   admin_net_netmask=$(facter "netmask_$admin_interface")
   eval $(ipcalc -np "$admin_net_ip" "$admin_net_netmask")
-  iptables -t nat -I POSTROUTING 1 -s "$NETWORK/$PREFIX" -p $proto -m $proto --dport $port -j ACCEPT
-  iptables -I FORWARD -i $admin_interface -o docker0  -m state --state NEW -p $proto  -m $proto --dport $port -j ACCEPT
+  #purge old rule
+  purge_iptables_rule "$container-$proto-$port-accept"
+  purge_iptables_rule "$container-$proto-$port-unmasquerade"
+
+  iptables -t nat -I POSTROUTING 1 -s "$NETWORK/$PREFIX" -p $proto -m $proto --dport $port -m comment --comment "$container-$proto-$port-unmasquerade" -j ACCEPT
+  iptables -A FORWARD -i $admin_interface -o docker0 -m state --state NEW -p $proto  -m $proto --dport $port -m comment --comment "$container-$proto-$port-accept" -j ACCEPT
   service iptables save
+}
+function purge_stale_iptables_rules {
+  container=$1
+  containername=${CONTAINER_NAMES[container]}
+  ports=$(docker inspect --format='{{ range $key, $value := .NetworkSettings.Ports }}{{ $key }} {{ end }}' $containername)
+  containerip=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' $containername)
+
+  for portproto in ports; do
+    port=$(echo $portproto | cut -d'/' -f1)
+    proto=$(echo $portproto | cut -d'/' -f2)
+      while read rule; do
+        #todo: parse ip as "-d (\d.\d.\d.\d)
+        #if ip != $containerip, drop it
+           #Match first IP from the rule
+        ruleip=$(echo $rule | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | head -1)
+        if [[ "$containerip" != "$ruleip" ]]; then
+          iptables-save | grep -v $rule | iptables-restore
+        fi
+      done < <(iptables-save | grep -- "-m $proto --dport $port")
+  done
+}
+
+function purge_iptables_rule {
+  comment="$1"
+  #method="deleteandsave"
+  method="savegreprestore"
+
+  if [ -z "$1" ]; then
+    echo "Error: No rule to match!" 1>&2
+    exit 1
+  fi
+
+  if [[ "$method" == "deleteandsave" ]];then
+    #Purge rules in filter table
+    for chain in INPUT FORWARD; do
+      while read lineno _; do
+        iptables -D $chain $lineno
+        service iptables save
+      done < <(iptables -t filter --line-numbers -L $chain | grep "/\* ${comment} \*/")
+    done
+
+    #Purge rules in nat table
+    for chain in POSTROUTING; do
+      while read lineno _; do
+        iptables -D $chain $lineno
+        service iptables save
+      done < <(iptables -t nat --line-numbers -L $chain | grep "/\* ${comment} \*/")
+    done
+  elif [[ "$method" == "savegreprestore" ]]; then
+    iptables-save | grep -v $comment | iptables-restore
+  fi
 }
 
 function remangle_nginx {
   #Necessary to forward packets to rsyslog with correct src ip
-  remangle_port tcp 8000
-  remangle_port tcp 8080
+  remangle_port nginx tcp 8000
+  remangle_port nginx tcp 8080
 }
 
 function remangle_syslog {
   #Necessary to forward packets to rsyslog with correct src ip
-  remangle_port tcp 514
-  remangle_port udp 514
+  remangle_port rsyslog tcp 514
+  remangle_port rsyslog udp 514
 }
 
 function setup_dhcrelay_for_cobbler {
@@ -548,7 +605,7 @@ function backup_compress {
     lrzopts="-L2"
   fi
   lrzip $lrzopts "$backup_dir/fuel_backup${image_suffix}.tar" -o "$backup_dir/fuel_backup${image_suffix}.tar.lrz"
-  
+
 }
 function backup_cleanup {
   echo "Cleaning up..."
