Fix blocking reject rule for rabbit ocf
* Make RMQ unblock call safe (remove all discovered RMQ
  blocking rules, if there are many of them).
* Use unblock safe call prior to the blocking one.
* Make block call idempotent and add 5 retries for iptables.
* Add info log messages about block/unblock actions. Notify
  if RMQ blocking rule cannot be added for some strange reason.

Partial-bug: #1373569
Closes-bug: #1375824

Change-Id: I46c6bf3c83ada4273eaa05530e80886ebac7e75f
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/deployment/puppet/nova/files/ocf/rabbitmq b/deployment/puppet/nova/files/ocf/rabbitmq
--- a/deployment/puppet/nova/files/ocf/rabbitmq
+++ b/deployment/puppet/nova/files/ocf/rabbitmq
@@ -280,12 +280,24 @@ reset_mnesia() {
 
 block_client_access()
 {
-    iptables -I INPUT -p tcp -m tcp --dport ${OCF_RESKEY_node_port} -m state --state NEW,RELATED,ESTABLISHED -m comment --comment 'temporary RMQ block' -j REJECT --reject-with tcp-reset
-
+    # do not add temporary RMQ blocking rule, if it is already exist
+    # otherwise, try to add a blocking rule with max of 5 retries
+    tries=0
+    until $(iptables -nvL | grep -q 'temporary RMQ block') || [[ $tries -gt 4 ]]; do
+      ((tries++))
+      sleep 1
+      iptables -I INPUT -p tcp -m tcp --dport ${OCF_RESKEY_node_port} -m state --state NEW,RELATED,ESTABLISHED \
+      -m comment --comment 'temporary RMQ block' -j REJECT --reject-with tcp-reset
+    done
 }
+
 unblock_client_access()
 {
-    iptables -D INPUT -p tcp -m tcp --dport ${OCF_RESKEY_node_port} -m state --state NEW,RELATED,ESTABLISHED -m comment --comment 'temporary RMQ block' -j REJECT --reject-with tcp-reset
+    # remove all temporary RMQ blocking rules, if there are more than one exist
+    for i in $(iptables -nvL --line-numbers | awk '/temporary RMQ block/ {print $1}'); do
+      iptables -D INPUT -p tcp -m tcp --dport ${OCF_RESKEY_node_port} -m state --state NEW,RELATED,ESTABLISHED \
+      -m comment --comment 'temporary RMQ block' -j REJECT --reject-with tcp-reset
+    done
 }
 
 get_nodes__base(){
@@ -664,8 +676,15 @@ start_rmq_server_app() {
 
 
     ocf_log info "${LH} begin."
-
+    # Safe-unblock the rules, if there are any
+    unblock_client_access
+    # Apply the blocking rule
     block_client_access
+    if [[ $? == 0 ]]; then
+      ocf_log info "${LH} blocked access to RMQ port"
+    else
+      ocf_log err "${LH} cannot block access to RMQ port!"
+    fi
     get_status
     if [[ $? != $OCF_SUCCESS ]] ; then
         ocf_log info "${LH} RMQ-runtime (beam) not started, starting..."
@@ -674,6 +693,7 @@ start_rmq_server_app() {
         if [ $rc -ne $OCF_SUCCESS ]
         then
             unblock_client_access
+            ocf_log info "${LH} unblocked access to RMQ port"
             return $OCF_ERR_GENERIC
         fi
     fi
@@ -706,6 +726,7 @@ start_rmq_server_app() {
                     ocf_log err "${LH} RMQ-server app can't be stopped during Mnesia cleaning. beam will be killed."
                     ocf_run killall -9 beam
                     unblock_client_access
+                    ocf_log info "${LH} unblocked access to RMQ port"
                     return $OCF_ERR_GENERIC
                 fi
             fi
@@ -717,6 +738,7 @@ start_rmq_server_app() {
     fi
     ocf_log info "${LH} end."
     unblock_client_access
+    ocf_log info "${LH} unblocked access to RMQ port"
     return $rc
 }
 
