Use separate pid files for Pacemaker OCF
W/o this change, improved pacemaker provider
would not differ OS-aware service pid file from
its own one. That would make impossible to
disable OS-aware services inside pcs provider.

The solution is to separate OS-aware layer from
pacemaker OCF one for pid/run/lock files (we use
only pid files in OCF scripts):

* Unify $OCF_RESKEY_pid_default definitions with
  $HA_RSCTMP and "$__SCRIPT_NAME" varaibles
* Add separate pid directories for resources managed
  by pacemaker OCF ($HA_RSCTMP/$__SCRIPT_NAME/)
  and keep pid files there to distinguish them from
  OS-aware ones.
* While $HA_RSCTMP is owned by root, chown resources'
  subdirectories $__SCRIPT_NAME to
  $OCF_RESKEY_user to grant daemons
  write access for their pid files as well.
* For status actions of OCF scripts, add safe creation
  and chowning of aforementioned pid directories
* Add missing user/group checks for rabbitmq ocf
* Add debug for pid file related actoins
* Make empty pidfile checks
* Fix pidfile creation on start action of neutron
  agents OCF
* Fix pidfile deletion on stop action for mysql OCF

DocImpact
Related blueprint pacemaker-improvements

Change-Id: I7f50e32ced83af8f32fd7907cb5fc723055da121
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/deployment/puppet/nova/files/ocf/rabbitmq b/deployment/puppet/nova/files/ocf/rabbitmq
--- a/deployment/puppet/nova/files/ocf/rabbitmq
+++ b/deployment/puppet/nova/files/ocf/rabbitmq
@@ -19,7 +19,7 @@ OCF_RESKEY_ctl_default="/usr/sbin/rabbitmqctl"
 OCF_RESKEY_debug_default=false
 OCF_RESKEY_username_default="rabbitmq"
 OCF_RESKEY_groupname_default="rabbitmq"
-OCF_RESKEY_pid_file_default=/var/run/rabbitmq/pid
+OCF_RESKEY_pid_file_default="${HA_RSCTMP}/${__SCRIPT_NAME}/${__SCRIPT_NAME}.pid"
 OCF_RESKEY_log_dir_default=/var/log/rabbitmq
 OCF_RESKEY_mnesia_base_default=/var/lib/rabbitmq/mnesia
 OCF_RESKEY_node_port_default=5672
@@ -249,6 +249,18 @@ rmq_setup_env() {
         chown -R ${OCF_RESKEY_username}:${OCF_RESKEY_groupname} ${PID_DIR}
         chmod 755 ${PID_DIR}
     fi
+    # check for user and group
+    getent passwd $OCF_RESKEY_username >/dev/null 2>&1
+    if [ ! $? -eq 0 ]; then
+        ocf_log err "User ${OCF_RESKEY_username} doesn't exit";
+        return $OCF_ERR_INSTALLED;
+    fi
+
+    getent group $OCF_RESKEY_groupname >/dev/null 2>&1
+    if [ ! $? -eq 0 ]; then
+        ocf_log err "Group ${OCF_RESKEY_groupname} doesn't exist";
+        return $OCF_ERR_INSTALLED;
+    fi
     export LL="${OCF_RESOURCE_INSTANCE}:"
 }
 
@@ -361,6 +373,7 @@ kill_rmq_and_remove_pid() {
             ocf_run kill -9 $pid
             ocf_log warn "${LH} RMQ-runtime (beam) PID=${pid} stopped by 'kill -9', sorry..."
         fi
+        ocf_log debug "${LH} Delete pid file: ${OCF_RESKEY_pid_file} with content ${pid}"
         ocf_run rm -f $OCF_RESKEY_pid_file
     fi
 }
@@ -507,6 +520,7 @@ stop_server_process() {
         # RMQ-server process can't stop succesfully
         if [[ -d /proc/$stop_pid/ ]] ; then
             ocf_run kill -9 $stop_pid
+            ocf_log warn "${LH} Cannot stop, killed stop process: ${stop_pid}"
         fi
     fi
 
@@ -575,7 +589,8 @@ start_beam_process() {
                 return $OCF_ERR_GENERIC
             fi
         fi
-        ocf_run rm -rf $OCF_RESKEY_pid_file
+        ocf_log debug "${LH} Delete pid file: ${OCF_RESKEY_pid_file} with content ${pid}"
+        ocf_run rm -f $OCF_RESKEY_pid_file
     fi
 
     # run beam process
@@ -590,6 +605,7 @@ start_beam_process() {
             # waiting for OCF_RESKEY_pid_file of beam process
             if [[ -f $OCF_RESKEY_pid_file ]] ; then
                 pid=$(cat ${OCF_RESKEY_pid_file})
+                ocf_log debug "${LH} Create pid file: ${OCF_RESKEY_pid_file} with content $(cat ${OCF_RESKEY_pid_file})"
                 break
             fi
             sleep 1
