[rpmcache] Improve repotrack error handling.

diff --git a/deployment/puppet/rpmcache/templates/build_rpm_cache.erb b/deployment/puppet/rpmcache/templates/build_rpm_cache.erb
--- a/deployment/puppet/rpmcache/templates/build_rpm_cache.erb
+++ b/deployment/puppet/rpmcache/templates/build_rpm_cache.erb
@@ -98,12 +98,20 @@ for tries in $(seq 1 <%= numtries %>); do
   env LANG=C rpm --checksig <%= pkgdir %>/Packages/* | grep 'md5 NOT OK' | cut -d':' -f1| xargs rm -f
   after=`ls -1 "<%= pkgdir %>/Packages/" |wc -l`
   echo Correct packages in local repo: $after
-  [ $before -eq $after ] || status=1
+  if [ $before -eq $after -a $status -eq 0 ]; then
+    break
+  fi
 done
+
 if [ $status -ne 0 ]; then
   echo "ERROR: Repotrack did not exit cleanly after <%= numtries %> tries."
   exit 1
 fi
+if [ $before -ne $after ]; then
+  echo "ERROR: There are still some packages with broken md5 sum after last (<%= numtries %>) retry to download them."
+  exit 1
+fi
+
 
 rm -f /etc/yum/vars/releasever
 yum-config-manager --enable 'nailgun' &> /dev/null
