fix retry in case repotrack produces error

diff --git a/deployment/puppet/rpmcache/templates/build_rpm_cache.erb b/deployment/puppet/rpmcache/templates/build_rpm_cache.erb
--- a/deployment/puppet/rpmcache/templates/build_rpm_cache.erb
+++ b/deployment/puppet/rpmcache/templates/build_rpm_cache.erb
@@ -133,7 +133,8 @@ echo "Building initial cache. This may take several minutes."
 yum --releasever=<%= releasever %> makecache
 
 for tries in $(seq 1 <%= numtries %>); do
-  /usr/local/bin/repotrack -a x86_64,noarch -p "<%= pkgdir %>/Packages" $(cat /etc/nailgun/required-rpms.txt | xargs echo -en)
+  #Retry if repotrack fails
+  /usr/local/bin/repotrack -a x86_64,noarch -p "<%= pkgdir %>/Packages" $(cat /etc/nailgun/required-rpms.txt | xargs echo -en) || continue
   status=$?
   #Purge any corrupt downloaded RPMs
   # FIXME: There is a error with a path substitution
@@ -149,7 +150,7 @@ for tries in $(seq 1 <%= numtries %>); do
   fi
 done
 
-if [ $status -ne 0 ]; then
+if [ "$status" -ne 0 ]; then
   echo "ERROR: Repotrack did not exit cleanly after <%= numtries %> tries." 1>&2
   exit 1
 fi
