Ensure logrotate's cron scripts exit with logrotate return code
Rewrite comment in logrotate-hourly to prevent possible confusion.

Closes-Bug: 1428116
Change-Id: Ie5fc660b5cc385f5e5015443f9a485ac0e7626d1

diff --git a/deployment/puppet/anacron/files/logrotate-hourly b/deployment/puppet/anacron/files/logrotate-hourly
--- a/deployment/puppet/anacron/files/logrotate-hourly
+++ b/deployment/puppet/anacron/files/logrotate-hourly
@@ -1,13 +1,15 @@
 #!/bin/sh
 # managed by puppet
 #
-# Due to bug existing, logrotate always returns 0. Use grep for detect errors:
-# would return 1 (considered as normal result), if logrotate returns no errors, return 0, if any. 
-#/usr/sbin/logrotate /etc/logrotate.d/20-fuel.conf >/dev/null 2>&1
+# Due to bug in logrotate, it always returns 0. Use grep for detect errors;
+# exit code 1 is considered a success as no errors were found.
+
 nice ionice -c3 /usr/sbin/logrotate /etc/logrotate.d/20-fuel*.conf >& /tmp/logrotate && grep -q error /tmp/logrotate
 
 EXITVALUE=$?
 if [ $EXITVALUE != 1 ]; then
     /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE] (1 was expected)"
+    exit 1
 fi
+
 exit 0
