Change the stop operation for neutron-dhcp-agent.
Bug shows that sometimes 5 sec is not enough to cleanup all namespaces and
processes in, especially when you have many tenants.
1. Add the sending of term signal to dhcp process every 3 second.
2. Increase the time what is left for cleaning up procedures when
OCF_RESKEY_CRM_meta_timeout is defined.

Change-Id: I71b8acc1da7171985854d08ad01a59d755d9d837
Closes-Bug: 1377906

diff --git a/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp b/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp
--- a/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp
+++ b/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp
@@ -449,27 +449,27 @@ neutron_dhcp_agent_stop() {
         #return $OCF_NOT_RUNNING
         return $OCF_SUCCESS
     fi
-    ocf_run kill -s TERM $pid
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack DHCP Server (${OCF_RESKEY_binary}) couldn't be stopped"
-        exit $OCF_ERR_GENERIC
-    fi
 
     # stop waiting
     shutdown_timeout=15
     if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
-        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
+        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-20))
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
+        ocf_run kill -s TERM $pid 2>&1 > /dev/null
+        rc=$?
+        if [ $rc -ne 0 ]; then
+            ocf_log err "OpenStack DHCP Server (${OCF_RESKEY_binary}) couldn't be stopped"
+            exit $OCF_ERR_GENERIC
+        fi
+        sleep 3
         neutron_dhcp_agent_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
-        count=`expr $count + 1`
-        sleep 1
+        count=`expr $count + 3`
         ocf_log debug "OpenStack DHCP Server (${OCF_RESKEY_binary}) still hasn't stopped yet. Waiting ..."
     done
 
