Ceph customizations for a project
DO NOT MERGE PLEASE!

Custom modifications for specific project.

Change-Id: Ife14703c06ec5f18ef77c6967b94caf675a49243

diff --git a/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp b/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp
--- a/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp
+++ b/deployment/puppet/neutron/files/ocf/neutron-agent-dhcp
@@ -36,6 +36,7 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
 OCF_RESKEY_binary_default="neutron-dhcp-agent"
 OCF_RESKEY_config_default="/etc/neutron/neutron.conf"
+OCF_RESKEY_keystone_config_default="/etc/keystone/keystone.conf"
 OCF_RESKEY_plugin_config_default="/etc/neutron/dhcp_agent.ini"
 OCF_RESKEY_log_file_default="/var/log/neutron/dhcp-agent.log"
 OCF_RESKEY_user_default="neutron"
@@ -44,6 +45,8 @@ OCF_RESKEY_os_auth_url_default="http://localhost:5000/v2.0"
 OCF_RESKEY_username_default="neutron"
 OCF_RESKEY_password_default="neutron_pass"
 OCF_RESKEY_tenant_default="services"
+OCF_RESKEY_rescheduling_tries_default=10
+OCF_RESKEY_rescheduling_interval_default=33
 OCF_RESKEY_debug_default='false'
 
 
@@ -53,10 +56,13 @@ OCF_RESKEY_debug_default='false'
 : ${OCF_RESKEY_tenant=${OCF_RESKEY_tenant_default}}
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
+: ${OCF_RESKEY_keystone_config=${OCF_RESKEY_keystone_config_default}}
 : ${OCF_RESKEY_plugin_config=${OCF_RESKEY_plugin_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
 : ${OCF_RESKEY_log_file=${OCF_RESKEY_log_file_default}}
+: ${OCF_RESKEY_rescheduling_tries=${OCF_RESKEY_rescheduling_tries_default}}
+: ${OCF_RESKEY_rescheduling_interval=${OCF_RESKEY_rescheduling_interval_default}}
 : ${OCF_RESKEY_debug=${OCF_RESKEY_debug_default}}
 
 
@@ -96,9 +102,9 @@ creates a distributed neutron-dhcp-agent cluster.
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack DHCP Server server binary (${OCF_RESKEY_binary})
+Location of the OpenStack DHCP Agent server binary (${OCF_RESKEY_binary})
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server server binary (${OCF_RESKEY_binary})</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Agent server binary (${OCF_RESKEY_binary})</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
@@ -106,15 +112,23 @@ Location of the OpenStack DHCP Server server binary (${OCF_RESKEY_binary})
 <longdesc lang="en">
 Location of the OpenStack Neutron Service (neutron-server) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (neutron-server) config file</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Agent (neutron-server) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
+</parameter>
+
+<parameter name="keystone_config" unique="0" required="0">
+<longdesc lang="en">
+Location of the Keystone configuration file
+</longdesc>
+<shortdesc lang="en">OpenStack Keystone config file</shortdesc>
+<content type="string" default="${OCF_RESKEY_keystone_config_default}" />
 </parameter>
 
 <parameter name="plugin_config" unique="0" required="0">
 <longdesc lang="en">
 Location of the OpenStack DHCP Service (${OCF_RESKEY_binary}) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (${OCF_RESKEY_binary}) config file</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Agent (${OCF_RESKEY_binary}) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_plugin_config_default}" />
 </parameter>
 
@@ -175,6 +189,21 @@ Admin tenant name
 <content type="string" default="${OCF_RESKEY_tenant_default}" />
 </parameter>
 
+<parameter name="rescheduling_tries" unique="0" required="0">
+  <longdesc lang="en">
+  Tries to start rescheduling script after start of agent.
+  </longdesc>
+  <shortdesc lang="en">Tries to start rescheduling script after start of agent.</shortdesc>
+  <content type="boolean" default="${OCF_RESKEY_rescheduling_tries_default}"/>
+</parameter>
+
+<parameter name="rescheduling_interval" unique="0" required="0">
+  <longdesc lang="en">
+  Interval between starts of rescheduling script.
+  </longdesc>
+  <shortdesc lang="en">Interval between starts of rescheduling script.</shortdesc>
+  <content type="boolean" default="${OCF_RESKEY_rescheduling_interval_default}"/>
+</parameter>
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
@@ -234,6 +263,21 @@ neutron_dhcp_agent_validate() {
     true
 }
 
+setup_auth() {
+    # setup token-based authentication if it possible
+    AUTH_TOKEN=""
+
+    if [[ -f $OCF_RESKEY_keystone_config ]] ; then
+        AUTH_TOKEN=$(grep -v '#' $OCF_RESKEY_keystone_config | grep -i 'admin_token\s*=\s*' | awk -F'=' '{print $2}')
+    fi
+
+    AUTH_TAIL=""
+    if [[ -n "$AUTH_TOKEN" ]] ; then
+        AUTH_TAIL="--admin-auth-url=${OCF_RESKEY_os_auth_url} --auth-token=${AUTH_TOKEN}"
+    fi
+
+    true
+}
 
 neutron_dhcp_agent_status() {
     local pid
@@ -300,11 +344,9 @@ clean_up() {
         if [ -z "$inside_ns_pids" ] ; then
             break
         fi
-        for ns_pid in $inside_ns_pids ; do
-          ocf_run kill $ns_pid
-        done
+        ocf_run kill $inside_ns_pids
         sleep 1
-        count=$(($count - 1))
+        ((count--))
     done
 
     # kill all remaining proceses, that not died by simple kill
@@ -344,7 +386,7 @@ neutron_dhcp_agent_start() {
     neutron_dhcp_agent_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) already running"
+        ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) already running"
         return $OCF_SUCCESS
     fi
 
@@ -365,16 +407,21 @@ neutron_dhcp_agent_start() {
         rc=$?
         [ $rc -eq $OCF_SUCCESS ] && break
         if [ $rc -ne $OCF_NOT_RUNNING ]; then
-            ocf_log err "OpenStack DHCP Server (${OCF_RESKEY_binary}) start failed"
+            ocf_log err "OpenStack DHCP Agent (${OCF_RESKEY_binary}) start failed"
             exit $OCF_ERR_GENERIC
         fi
         sleep 3
     done
 
     # detach deffered rescheduling procedure
-    bash -c "sleep 33 ; q-agent-cleanup.py --agent=dhcp --reschedule --remove-dead 2>&1 >> /var/log/neutron/rescheduling.log" &
+    RESCHEDULING_CMD="q-agent-cleanup.py --agent=dhcp --reschedule --remove-dead ${AUTH_TAIL} 2>&1 >> /var/log/neutron/rescheduling.log"
+    RESCH_CMD=''
+    for ((i=0; i<$OCF_RESKEY_rescheduling_tries; i++)) ; do
+        RESCH_CMD="$RESCH_CMD sleep $OCF_RESKEY_rescheduling_interval ; $RESCHEDULING_CMD ;"
+    done
+    bash -c "$RESCH_CMD" &
 
-    ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) started"
+    ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) started"
     return $OCF_SUCCESS
 }
 
@@ -387,7 +434,7 @@ neutron_dhcp_agent_stop() {
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
         clean_up
-        ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) already stopped"
+        ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) already stopped"
         sleep 1
         clean_up_namespaces
         return $OCF_SUCCESS
@@ -395,50 +442,61 @@ neutron_dhcp_agent_stop() {
 
     #Try SIGTERM
     pid=`get_worker_pid`
-    if [ "xxx$pid" == "xxx" ] ; then
-        ocf_log warn "OpenStack DHCP Server (${OCF_RESKEY_binary}) not running."
-        #return $OCF_NOT_RUNNING
-        return $OCF_SUCCESS
-    fi
-    ocf_run kill -s TERM $pid
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack DHCP Server (${OCF_RESKEY_binary}) couldn't be stopped"
-        exit $OCF_ERR_GENERIC
-    fi
-
     # stop waiting
     shutdown_timeout=15
+    iteration_time=3
     if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
-        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
+        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-6))
     fi
+    all_inside_ns_pids=`get_pid_list_for_ns_list $(get_ns_list)`
+    all_pids="$pid $all_inside_ns_pids"
     count=0
-    while [ $count -lt $shutdown_timeout ]; do
-        neutron_dhcp_agent_status
-        rc=$?
-        if [ $rc -eq $OCF_NOT_RUNNING ]; then
-            break
+    alive=1
+    while [ $alive -gt 0 ] && [ $count -lt $shutdown_timeout ]; do
+        alive=0
+        ocf_run kill -s TERM $all_pids
+        sleep $iteration_time
+        #Check if processes are alive after command kill
+        #if yes, send to them the term signal again
+        np=""
+        for pid in $all_pids ; do
+            ocf_run kill -s 0 $pid
+            if [ $? -eq 0 ]; then
+                np="$np $pid"
+                ((alive++))
+            fi
+        done
+        if [ $alive -gt 0 ] ; then
+            all_pids=$np
         fi
-        count=`expr $count + 1`
-        sleep 1
-        ocf_log debug "OpenStack DHCP Server (${OCF_RESKEY_binary}) still hasn't stopped yet. Waiting ..."
+        ((count+=$iteration_time))
+        ocf_log debug "OpenStack DHCP Agent (${OCF_RESKEY_binary}) still hasn't stopped yet. Waiting ..."
     done
-
-    neutron_dhcp_agent_status
-    rc=$?
-    if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) failed to stop after ${shutdown_timeout}s \
-          using SIGTERM. Trying SIGKILL ..."
-        ocf_run kill -s KILL $pid
+    #Send the kill signal to processes which are still alive
+    if [ $alive -gt 0 ] ; then
+        alive=0
+        ocf_run kill -s KILL $all_pids
+        sleep 1
+        for pid in $all_pids ; do
+            ocf_run kill -s 0 $pid
+            if [ $? -eq 0 ]; then
+                ((alive++))
+            fi
+        done
+        if [ $alive -gt 0 ] ; then
+            ocf_log err "OpenStack DHCP Agent (${OCF_RESKEY_binary}) stop failed"
+            return $OCF_ERR_GENERIC
+        fi
     fi
-    ocf_log info "OpenStack DHCP Server (${OCF_RESKEY_binary}) stopped"
+    ocf_log info "OpenStack DHCP Agent (${OCF_RESKEY_binary}) stopped"
 
     rm -f $OCF_RESKEY_pid
 
-    clean_up
-    sleep 1
+#   cleanup network interfaces
+    q-agent-cleanup.py --agent=dhcp --cleanup-ports
     clean_up_namespaces
+    q-agent-cleanup.py --agent=dhcp --remove-self ${AUTH_TAIL} 2>&1 >> /var/log/neutron/rescheduling.log &
+    sleep 3
 
     return $OCF_SUCCESS
 }
@@ -454,6 +512,8 @@ esac
 
 # Anything except meta-data and help must pass validation
 neutron_dhcp_agent_validate || exit $?
+setup_auth || exit $?
+umask 0022
 
 # What kind of method was invoked?
 case "$1" in
