Make log rotation more bulletproof
- use flock to ensure that only one instance of fuel-logrotate is running
- enable delayed compression in system-wide logrotate.conf to avoid race
  condition between fuel-logrotate and regular logrotate
- enable delaycompress also on master node
- use bash to execute fuel-logrotate
- fix path to cron's logrotate script in logrotate-debug

This commit changes default behavior of logrotate by enabling compress
and delaycompress. The result is that compression is enabled for all log
files managed by logrotate and rotated logs are compressed only on the next
rotation. It allows us to resolve rotation cycle that might happen when
both regular logrotate and fuel-logrotate were executed at the same
time, causing both to rotate the same file.

Closes-Bug: 1461400
Doc-Impact: ops guide
Change-Id: I94c497a8916fa6fac87ea2ddc51f6de56ab73f98
Co-Authored-By: Alex Schultz <aschultz@mirantis.com>

diff --git a/files/fuel-misc/logrotate-ubuntu b/files/fuel-misc/logrotate-ubuntu
--- a/files/fuel-misc/logrotate-ubuntu
+++ b/files/fuel-misc/logrotate-ubuntu
@@ -1,27 +1,39 @@
-#!/bin/sh
+#!/bin/bash
 # managed by puppet
-# Clean non existent log file entries from status file
-cd /var/lib/logrotate
-test -e status || touch status
-head -1 status > status.clean
-sed 's/"//g' status | while read logfile date
-do
-    [ -e "$logfile" ] && echo "\"$logfile\" $date"
-done >> status.clean
-mv status.clean status
-test -x /usr/sbin/logrotate || exit 0
+
+lock() {
+    exec 903>/var/lock/fuel-logrotate
+    flock -n 903 && return 0 || return 1
+}
+
+fail() {
+    if [ -z "$1" ]
+    then
+        MESSAGE="WARNING logrotate failed, no reason provided"
+    else
+        MESSAGE=$1
+    fi
+    /usr/bin/logger -t logrotate "${MESSAGE}"
+    exit 1
+}
+
+unlock() {
+    flock -n 903
+}
+
+lock || fail "WARNING logrotate flock failed, exiting"
 
 if ! pgrep -x logrotate >/dev/null 2>&1; then
     nice ionice -c3 /usr/sbin/logrotate /etc/logrotate.d/fuel.nodaily
     EXITVALUE=$?
 else
-    /usr/bin/logger -t logrotate "WARNING another logrotate instance is already running, exiting"
-    exit 1
+    fail "WARNING another logrotate instance is already running, exiting"
 fi
 
 if [ $EXITVALUE != 0 ]; then
-    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE] (0 was expected)"
+    fail "ALERT exited abnormally with [$EXITVALUE] (0 was expected)"
 fi
 
+unlock
 exit $EXITVALUE
 
